---
title: "Eligible at 2Y"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = '', warning=FALSE)
```

```{r include=FALSE}
library(readxl)
library(data.table)
library(magrittr)
library(yaml)
library(glue)
f <- glue

source('basic.R')


xls_path <- '../../data/ESSG extractions_july 21/ESSG extraction July 2021 DEF.xlsx'

clinical_data <- read_excel(xls_path) %>% 
  as.data.table()

analysis_vars <- read_yaml('descriptive.yml')
discarded_patients <- readLines('discarded_patients')
```

```{r}
setnames(clinical_data, 'Major curve Cobb angle', 'Static Major curve Cobb angle')
setnames(clinical_data, 'ODI - Score (%)_First Visit', 'ODI - Score (%)')
setnames(clinical_data, 'SRS22 - Function_First Visit', 'SRS22 - Function / Activity')
setnames(clinical_data, 'SRS22 - Pain_First Visit', 'SRS22 - Pain')
setnames(clinical_data, 'SRS22 -SI_First Visit', 'SRS22 - Self image / Appearance')
setnames(clinical_data, 'SRS22 - MH_First Visit', 'SRS22 - Mental health')
setnames(clinical_data, 'SRS22 - SRS Subtotal score_First Visit', 'SRS22 - SRS Subtotal score')
setnames(clinical_data, 'SF36 - PCS_First Visit', 'SF36 - PCS')
setnames(clinical_data, 'SF36 - MCS_First Visit', 'SF36 - MCS') 
```

```{r}
uiv_ <- c('T10', 'T11', 'T12', 'L1')
clinical_data %>% 
  .[, upper:= substr(`Posterior Instrumented Fusion: Upper / Lower Levels`, 1, 2)] %>% 
  .[, uiv_t10_12_l1 := ifelse(upper %in% uiv_, 'Yes', 'No')]
analysis_vars$surgery <- c(analysis_vars$surgery, 'uiv_t10_12_l1')

clinical_data %>% 
  .[grepl('Ex', `Tobacco use_First Visit`, fixed=TRUE),
    `Tobacco use_First Visit` := 'Ex'] %>% 
  .[grepl('Current', `Tobacco use_First Visit`, fixed=TRUE), 
    `Tobacco use_First Visit` := 'Current'] 

clinical_data %<>% 
  .[, followup_2y := 
      !is.na(`2 YEAR VISIT - Date of visit`) | 
      !is.na(`3 YEAR VISIT - Date of visit`)] %>% 
  .[, followup_5y := 
      !is.na(`5 YEAR VISIT - Date of visit`) | 
      !is.na(`6 YEAR VISIT - Date of visit`)]

clinical_data[, `ASA classification` := as.character(`ASA classification`)]
```

```{r}
stats_fun <- function(variable){
  if( class(variable) == 'numeric' ){
    return( list(
      mean = mean(variable, na.rm=TRUE),
      sd = sd(variable, na.rm = TRUE)
    ))
  }else{
    res_table <- table(variable)
    return(list(
      table = res_table, 
      proportion = prop.table(res_table)
    ))
  }
}
```

# Selection

```{r echo=TRUE}
clinical_data %>% 
  .[Study=='Op'] %>% 
  .[Site != 'ANK Op'] %>% 
  .[`Vital status` == 'Alive'] %>% 
  .[!(`Code of the patient` %in% discarded_patients)] %>% 
  .[`st1. Date of Stage` %>% as.Date() < as.Date('2018-09-01')] ->
  data_
```

Total Patients: `r data_[, .N]`

```{r}
data_[, .N, Site]
```


### Demographics
```{r echo=FALSE, comment=""}
for(var_ in analysis_vars$demographics ){
  cat(var_)
  cat('\n')
  res <- stats_fun(data_[[var_]])
  for( res_name in names(res) ){
    print(res_name)
    print(res[[res_name]])
  }
  cat('\n\n')
}
```


### Radiology
```{r echo=FALSE, comment=""}
for(var_ in analysis_vars$radiology ){
  var_6w <- "6W. {var_}" %>% f
  var_2y <- "2Y. {var_}" %>% f
  var_5y <- "5Y. {var_}" %>% f
  vars_years <- c(var_, var_6w, var_2y, var_5y)
  for(var_y in vars_years){
    cat(var_y)
    cat('\n')
    res <- stats_fun(data_[[var_y]])
    for( res_name in names(res) ){
      print(res_name)
      print(res[[res_name]])
    }
    cat('\n\n')
  }

    
  cat('{var_} tests\n' %>% f)
  val_ <- data_[[var_]]
  val_6w <- data_[[var_6w]]
  val_2y <- data_[[var_2y]]
  val_5y <- data_[[var_5y]]
  cat('\nPreop vs 6w p-value\n')
  cat(t.test(val_6w , val_)$p.val)
  cat('\n\n')
  cat('Preop vs 2y p-value\n')
  cat(t.test(val_2y, val_)$p.val)
  cat('\n\n')
  cat('Preop vs 5y p-value\n')
  cat(t.test(val_5y, val_)$p.val)
  cat('\n\n')
  cat('6w vs 2y p-value\n')
  cat(t.test(val_2y, val_6w)$p.val)
  cat('\n\n')
  cat('2y vs 5y p-value\n')
  cat(t.test(val_5y, val_2y)$p.val)
  cat('\n\n')
}
```


### Quality of Life
```{r echo=FALSE, comment=""}
for(var_ in analysis_vars$quality ){
  var_6m <- "6M. {var_}" %>% f
  var_2y <- "2Y. {var_}" %>% f
  var_5y <- "5Y. {var_}" %>% f
  vars_years <- c(var_, var_2y, var_5y)
  for(var_y in vars_years){
    cat(var_y)
    cat('\n')
    res <- stats_fun(data_[[var_y]])
    for( res_name in names(res) ){
      print(res_name)
      print(res[[res_name]])
    }
    cat('\n\n')
  }
  
  cat('{var_} tests\n' %>% f)
  val_ <- data_[[var_]]
  val_6m <- data_[[var_6m]]
  val_2y <- data_[[var_2y]]
  val_5y <- data_[[var_5y]]
  cat('\nPreop vs 6w p-value\n')
  cat(t.test(val_6m, val_)$p.val)
  cat('\n')
  cat('\nPreop vs 2y p-value\n')
  cat(t.test(val_2y, val_)$p.val)
  cat('\n\n')
  cat('\nPreop vs 5y p-value\n')
  cat(t.test(val_5y, val_)$p.val)
  cat('\n')
  cat('2y vs 5y p-value\n')
  cat(t.test(val_5y, val_2y)$p.val)
  cat('\n\n')
}
```


### Surgery
```{r echo=FALSE, comment=""}
for(var_ in analysis_vars$surgery ){
  cat(var_)
  cat('\n')
  res <- stats_fun(data_[[var_]])
  for( res_name in names(res) ){
    print(res_name)
    print(res[[res_name]])
  }
  cat('\n\n')
}
```

