---
title: "5y followup analysis"
output: html_document
---

  
```{r setup, include=FALSE}
knitr::opts_knit$set(
  echo = FALSE, 
  root.dir=normalizePath('../../'),
  warning=FALSE, 
  comment="",
  message=FALSE
)
```

```{r warning=FALSE, echo=FALSE, include=FALSE}
library(stringr)
library(ggplot2)
library(zeallot)
library(gridExtra)
library(Hmisc)

source('code/five_years/five_years-utils.R')

ncols_plots <- 2

outcomes <- c(
  '5Y. ODI - Score (%)', '5Y. SRS22 - SRS Subtotal score', '5Y. SF36 - PCS', '5Y. SF36 - MCS'
)

c(data_set_0, predictive_vars, .) %<-% get_data(clean=FALSE)
data_set <- data_set_0 %>% 
  .[Site != "MAD Op"] %>% 
  copy

xls_path <- 'data/ESSG extraction July 2020_3.xlsx'

complications <- read_excel(xls_path, sheet='Complications') %>%
  as.data.table %>%
  .[`Complication Impact` == 'Major Complication']


demographics <- read_yaml('code/five_years/demographic.yml')
demographics_all <- demographics %>% unlist


outcomes %>% 
  lapply(. %>% str_replace_all('5', '2')) ->
  outcomes_2y
names(outcomes_2y) <- outcomes

outcomes %>% 
  lapply(. %>% str_replace_all('5', '6')) ->
  outcomes_6y
names(outcomes_6y) <- outcomes

outcomes %>% 
  sapply(. %>% get_base_outcome(first_visit=TRUE)) ->
  base_outcomes 

for( outcome in names(outcomes_6y)){
  outcome_6y <- outcomes_6y[[outcome]]
  data_set %<>%
    .[is.na(get(outcome)), c(outcome_6y) := get(outcome)]
}

outcome_2y <- outcomes_2y[[1]]
outcome <- outcomes[[1]]


study_vars <- c(
  outcomes, outcomes_2y %>% unlist, demographics_all, base_outcomes, 'Code of the patient'
) %>% unique
data_set %<>% 
  .[Study=='Op'] %>% 
  .[, .SD, .SDcols=study_vars] %>% 
  .[, followup_2y := 'has_followup'] %>% 
  .[is.na(get(outcome_2y)), followup_2y := 'no_followup'] %>% 
  .[, followup_5y := 'has_followup'] %>% 
  .[is.na(get(outcome)), followup_5y := 'no_followup'] 

```

- Patients with at least 2 year from intervention: `r "{data_set[, .N]}" %>% f`
- Patients with 2y info: `r "{data_set[followup_2y == 'has_followup', .N]}" %>% f`
- Patients with 5y info: `r "{data_set[followup_5y == 'has_followup', .N]}" %>% f`


```{r echo=FALSE}
patients_complications_5y <- complications %>%
  .[`Days since surgery` >= 365*2 ] %>% 
  .[`Days since surgery` < 365*5 ] %>% 
  .[, `Code of the patient`]
patients_complications_2y <- complications %>%
  .[`Days since surgery` < 365*2 ] %>% 
  .[, `Code of the patient`]

data_ <- data_set %>%
  copy %>%
  .[, complication_before_2y:='No'] %>%
  .[`Code of the patient` %in% patients_complications_2y, complication_before_2y:='Yes'] %>% 
  .[ followup_2y == FALSE, complication_before_2y:=NA] %>%
  .[, complication_2y_5y:='No'] %>%
  .[`Code of the patient` %in% patients_complications_5y, complication_2y_5y:='Yes'] %>% 
  .[ followup_5y == FALSE, complication_2y_5y:=NA]
```

### Complications during 2y depending on followup 5y
```{r echo=FALSE}
data_ %>% 
  .[followup_2y=='has_followup'] %>% 
  .[, .(
    complication_before_2y=mean(complication_before_2y=='Yes'),
    low_ci=binconf(sum(complication_before_2y=='Yes'), .N)[2],
    up_ci=binconf(sum(complication_before_2y=='Yes'), .N)[3]
    ), followup_5y]
```



### HRQOL during 2y depending on followup 5y
```{r echo=FALSE, comment=""}
for( outcome in outcomes ){
  outcome_2y <- outcomes_2y[[outcome]]
  cat(outcome_2y)
  cat('\n')
  data_ %>% 
    .[followup_2y=='has_followup'] %>% 
    .[, .(
      mean_outcome = mean(get(outcome_2y), na.rm=TRUE),
      sd_outcome = sd(get(outcome_2y), na.rm=TRUE)/sqrt(.N)
    ), followup_5y] %>% print
  
    
  p_val <- t.test(
    data_[followup_2y=='has_followup' & followup_5y == 'has_followup',
      get(outcome_2y)],
    data_[followup_2y=='has_followup' & followup_5y == 'no_followup',
      get(outcome_2y)]
  )
  
  print("t-test p-value: {p_val$p.value}" %>% f)
}
```



# Follow up


```{r echo=FALSE, include=FALSE}
demo_plots <- list()
for(demo_var in demographics_all){
  if( class(data_set[, get(demo_var)]) == 'numeric' ){
    data_set %>% 
      copy() %>% 
      setnames(demo_var, 'demo_var') %>% 
      .[, .(demo_var, followup_2y, followup_5y)] %>% 
      melt(id.vars='demo_var') %>% 
      ggplot(aes(variable, demo_var, fill=value)) +
      geom_boxplot() + 
      coord_flip() +
      xlab('Info') +
      ylab(demo_var) + 
      scale_color_discrete(labels = c(outcome, outcomes_2y[[outcome]]))  ->
      demo_plots[[demo_var]]
  }else{
    data_set %>% 
      copy() %>% 
      setnames(demo_var, 'demo_var') %>% 
      .[, .(followup=sum(followup_5y=='has_followup')/sum(followup_2y=='has_followup')), 
      demo_var
      ] %>% 
      ggplot(aes(demo_var, followup, fill=demo_var)) +
      geom_col() + 
      xlab(demo_var) +
      ylab('Ratio 5y / 2y followup') +
      theme(axis.text.x = element_text(angle = 10, vjust = 0.5, hjust=1)) ->
      demo_plots[[demo_var]]
  }
}
```


```{r echo=FALSE, message=FALSE, fig.height=30, fig.width=10, warning=FALSE}
do.call("grid.arrange", c(demo_plots, ncol=ncols_plots))
```

```{r echo=FALSE, comment=""}
data_set %>% 
  copy %>% 
  .[, followup_5y:=ifelse(followup_5y=='has_followup', 'Yes', 'No')] %>% 
  .[, followup_2y:=ifelse(followup_2y=='has_followup', 'Yes', 'No')] ->
  data_set_

htmltools::h3('Followup')
models <- variable_effect(data_set_, 'followup_5y', 'followup_2y', demographics)
htmltools::h5('Demographics')
models$demographic %>% print
htmltools::h5('Radiology')
models$radiology %>% print
```



# 5y selection bias

## Demographics

```{r echo=FALSE, comment=""}
sel_cols <- c(
  demographics$demographic,
  "followup_5y"
)

data_set %>% 
  .[followup_2y=='has_followup'] %>% 
  .[, followup_5y:=ifelse(followup_5y=='has_followup', 1, 0)] %>% 
  .[, .SD, .SDcols = sel_cols] ->
  data_set_

glm(followup_5y~., data = data_set_) %>% get_model_info() %>% print
```


## Radiology
```{r echo=FALSE, comment=""}
sel_cols <- c(
  demographics$demographic,
  demographics$radiologic,
  "followup_5y"
)

data_set %>% 
  .[followup_2y=='has_followup'] %>% 
  .[, followup_5y:=ifelse(followup_5y=='has_followup', 1, 0)] %>% 
  .[, .SD, .SDcols = sel_cols] ->
  data_set_

glm(followup_5y~., data = data_set_) %>% get_model_info() %>% print
```


## Increment of quality of life
```{r echo=FALSE, comment=""}
qualitylife <- demographics$qualitylife %>% 
  sapply(. %>% get_base_outcome(first_visit = TRUE), USE.NAMES = TRUE) %>% 
  as.list

sel_cols <- c(
  demographics$demographic,
  demographics$radiologic,
  demographics$qualitylife,
  qualitylife %>% unlist,
  "followup_5y"
)

data_set %>% 
  .[followup_2y=='has_followup'] %>% 
  .[, followup_5y:=ifelse(followup_5y=='has_followup', 1, 0)] %>% 
  .[, .SD, .SDcols = sel_cols] ->
  data_set_

for( qual_var in demographics$qualitylife){
  inc_qual_var <- "{qual_var}_inc" %>% f
  data_set_[, c(inc_qual_var) := get(qual_var) - get(qualitylife[[qual_var]])]
  data_set_[, c(qual_var) := NULL]
  data_set_[, c(qualitylife[[qual_var]]) := NULL]
}

glm(followup_5y~., data = data_set_) %>% get_model_info()
```

# MCIDS

```{r echo=FALSE, comment=""}
mcids <- list()
mcids[['5Y. ODI - Score (%)']] <- 12.8
mcids[['5Y. SRS22 - SRS Subtotal score']] <- 0.43
mcids[['5Y. SF36 - PCS']] <- 4.9
mcids
```


```{r echo=FALSE, comment=""}
base_mcids <- mcids %>% names %>% 
  sapply(. %>% get_base_outcome(first_visit = TRUE), USE.NAMES = TRUE) %>% 
  as.list

data_set_ <- data_set %>% copy()

res <- data.frame()
for( qual_var_5y in mcids %>% names ){
  qual_var_root <- gsub("5Y. ", "", qual_var_5y)
  base_qual_var <- base_mcids[[qual_var_5y]] 
  qual_var_2y <- outcomes_2y[[qual_var_5y]]
  inc_qual_var_5y <- "{qual_var_5y}_inc" %>% f
  inc_qual_var_2y <- "{qual_var_2y}_inc" %>% f
  inc_qual_var_5y_2y <- "{qual_var_root}_5y_2y_inc" %>% f


  data_set_[, c(inc_qual_var_2y) := get(qual_var_2y) - get(base_qual_var)]
  data_set_[, c(inc_qual_var_5y) := get(qual_var_5y) - get(base_qual_var)]
  data_set_[, c(inc_qual_var_5y_2y) := get(qual_var_5y) - get(qual_var_2y)]

  
  if( grepl('ODI', qual_var_5y, fixed=TRUE) ){
    inc_2y_prop <- data_set_ %>%
      .[, get(inc_qual_var_2y) < -mcids[[qual_var_5y]]] %>% na.omit() 
    inc_5y_prop <- data_set_ %>%
      .[, get(inc_qual_var_5y) < -mcids[[qual_var_5y]]] %>% na.omit() 
    inc_5y_2y_prop <- data_set_ %>%
      .[, get(inc_qual_var_5y_2y) < -mcids[[qual_var_5y]]] %>% na.omit() 
  }else{
    inc_2y_prop <- data_set_ %>%
      .[, get(inc_qual_var_2y) > mcids[[qual_var_5y]]] %>% na.omit() 
    inc_5y_prop <- data_set_ %>%
      .[, get(inc_qual_var_5y) > mcids[[qual_var_5y]]] %>% na.omit() 
    inc_5y_2y_prop <- data_set_ %>%
      .[, get(inc_qual_var_5y_2y) > mcids[[qual_var_5y]]] %>% na.omit()
  }

  
  p_val <- prop.test(
    c(sum(inc_2y_prop), sum(inc_5y_prop)),
    c(len(inc_2y_prop), len(inc_5y_prop))
  )
  
  inc_2y_percent <- inc_2y_prop %>% mean %>% round(3)
  inc_5y_percent <- inc_5y_prop %>% mean %>% round(3)
  inc_5y_2y_percent <- inc_5y_2y_prop %>% mean %>% round(3)

  
  res %<>% rbind(data.frame(
    variable = qual_var_root,
    inc_2y_percent = inc_2y_percent * 100,
    inc_5y_percent = inc_5y_percent * 100,
    p_val_two_previous = p_val$p.value %>% round(3),
    inc_5y_2y_percent = inc_5y_2y_percent * 100
  ))  
}

res
```

# PASS

```{r echo=FALSE, comment=""}
pass <- list()
pass[['5Y. ODI - Score (%)']] <- 18
pass[['5Y. SRS22 - SRS Subtotal score']] <- 3.5
pass
```


```{r echo=FALSE, comment=""}
base_pass <- pass %>% names %>% 
  sapply(. %>% get_base_outcome(first_visit = TRUE), USE.NAMES = TRUE) %>% 
  as.list

data_set_ <- data_set %>% copy()

res <- data.frame()
for( qual_var_5y in pass %>% names ){
  qual_var_root <- gsub("5Y. ", "", qual_var_5y)
  base_qual_var <- base_pass[[qual_var_5y]] 
  qual_var_2y <- outcomes_2y[[qual_var_5y]]
  
  prop_2y <- data_set_ %>%
    .[, get(qual_var_2y) < pass[[qual_var_5y]]] %>% na.omit() 
  prop_5y <- data_set_ %>%
    .[, get(qual_var_5y) < pass[[qual_var_5y]]] %>% na.omit() 
  
  p_val <- prop.test(
    c(sum(prop_2y), sum(prop_5y)),
    c(len(prop_2y), len(prop_5y))
  )
  
  prop_2y <- prop_2y %>% mean %>% round(3)
  prop_5y <- prop_5y %>% mean %>% round(3)

  
  res %<>% rbind(data.frame(
    variable = qual_var_root,
    prop_2y = prop_2y * 100,
    prop_5y = prop_5y * 100,
    p_val = p_val$p.value %>% round(3)
  ))  
}

res
```

