---
title: "5y quality life analysis"
output: html_document
---

  
```{r setup, include=FALSE}
knitr::opts_knit$set(
  echo = FALSE, 
  root.dir=normalizePath('../../'),
  warning=FALSE, 
  comment="",
  message=FALSE
)
```

```{r warning=FALSE, echo=FALSE, include=FALSE}
library(stringr)
library(ggplot2)
library(zeallot)
library(gridExtra)
library(DiagrammeR)

source('code/five_years/five_years-utils.R')

ncols_plots <- 2

outcomes <- c(
  '5Y. ODI - Score (%)', '5Y. SRS22 - SRS Subtotal score', '5Y. SF36 - PCS', '5Y. SF36 - MCS', 
  '5Y. SRS22 - Satisfaction with management'
)

c(data_set_0, predictive_vars, .) %<-% get_data(clean=FALSE)
data_set <- data_set_0 %>% copy

demographics <- read_yaml('code/five_years/demographic.yml')
demographics_all <- demographics %>% unlist

outcomes %>% 
  lapply(. %>% str_replace_all('5', '2')) ->
  outcomes_2y
names(outcomes_2y) <- outcomes

outcomes %>% 
  lapply(. %>% str_replace_all('5', '6')) ->
  outcomes_6y
names(outcomes_6y) <- outcomes

outcomes %>% 
  sapply(. %>% get_base_outcome(first_visit=TRUE)) ->
  base_outcomes 

for( outcome in names(outcomes_6y)){
  outcome_6y <- outcomes_6y[[outcome]]
  data_set %<>%
    .[is.na(get(outcome)), c(outcome_6y) := get(outcome)]
}

outcome_2y <- outcomes_2y[[1]]
outcome <- outcomes[[1]]

if( 'SRS22 - Satisfaction_First Visit' %in% colnames(data_set) ){
  setnames(data_set, 'SRS22 - Satisfaction_First Visit', 'SRS22 - Satisfaction with management_First Visit')
}

study_vars <- c(outcomes, outcomes_2y %>% unlist, demographics_all, base_outcomes) %>% unique
data_set %<>% 
  .[Study=='Op'] %>% 
  .[, .SD, .SDcols=study_vars] %>% 
  .[, followup_2y := 'has_followup'] %>% 
  .[is.na(get(outcome_2y)), followup_2y := 'no_followup'] %>% 
  .[, followup_5y := 'has_followup'] %>% 
  .[is.na(get(outcome)), followup_5y := 'no_followup'] 

get_model_info <- . %>% summary %>% coefficients %>% round(3)
```

```{r echo=FALSE}
grViz('
digraph rmarkdown {

  graph [
    rankdir = UD
  ]
  
  node [
    shape=circle,
    fixedsize=true,
    width=1.2,
    style=filled,
    fillcolor=aquamarine2,
    fontsize=15
    ]

 
  D[label="Demographic"]
  R[label="Radiologic\n(Deformity)"]
  O[label="Outcome"]
  
  D -> R 
  D -> O
  R -> O
  
}                  
')
```

```{r echo=FALSE, comment=""}
demographics %>% as.yaml %>% cat
```

# Scores

```{r echo=FALSE}
outcome <- outcomes[1]
htmltools::h1(outcome)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
data_set[, 
  .SD, 
  .SDcols=c(get_base_outcome(outcome, first_visit=TRUE), outcomes_2y[[outcome]], outcome)
] %>% 
  melt() %>% 
  ggplot(aes(variable, value)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 10, vjust = 0.5, hjust=1))
```

<!-- ```{r echo=FALSE, include=FALSE} -->
<!-- demo_plots <- plot_scores(data_set, outcome, demographics_all) -->
<!-- ``` -->

<!-- ```{r echo=FALSE, message=FALSE, fig.height=30, fig.width=10, warning=FALSE} -->
<!-- do.call("grid.arrange", c(demo_plots, ncol=ncols_plots)) -->
<!-- ``` -->

```{r echo=FALSE, comment=""}
htmltools::h3(outcome)
models <- variable_effect(data_set, outcome, outcomes_2y[[outcome]], demographics)
htmltools::h5('Demographics')
models$demographic %>% print
htmltools::h5('Radiology')
models$radiology %>% print
```


```{r echo=FALSE, comment=""}
outcome <- outcomes[2]
htmltools::h1(outcome)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}

data_set[, 
  .SD, 
  .SDcols=c(get_base_outcome(outcome, first_visit=TRUE), outcomes_2y[[outcome]], outcome)
] %>% 
  melt() %>% 
  ggplot(aes(variable, value)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 10, vjust = 0.5, hjust=1))
```

<!-- ```{r echo=FALSE, include=FALSE} -->
<!-- demo_plots <- plot_scores(data_set, outcome, demographics_all) -->
<!-- ``` -->


<!-- ```{r echo=FALSE, message=FALSE, fig.height=30, fig.width=10, warning=FALSE} -->
<!-- do.call("grid.arrange", c(demo_plots, ncol=ncols_plots)) -->
<!-- ``` -->


```{r echo=FALSE, comment=""}
htmltools::h3(outcome)
models <- variable_effect(data_set, outcome, outcomes_2y[[outcome]], demographics)
htmltools::h5('Demographics')
models$demographic %>% print
htmltools::h5('Radiology')
models$radiology %>% print
```


```{r echo=FALSE}
outcome <- outcomes[3]
htmltools::h1(outcome)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}

data_set[, 
  .SD, 
  .SDcols=c(get_base_outcome(outcome, first_visit=TRUE), outcomes_2y[[outcome]], outcome)
] %>% 
  melt() %>% 
  ggplot(aes(variable, value)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 10, vjust = 0.5, hjust=1))
```

<!-- ```{r echo=FALSE, include=FALSE} -->
<!-- demo_plots <- plot_scores(data_set, outcome, demographics_all) -->
<!-- ``` -->


<!-- ```{r echo=FALSE, message=FALSE, fig.height=30, fig.width=10, warning=FALSE} -->
<!-- do.call("grid.arrange", c(demo_plots, ncol=ncols_plots)) -->
<!-- ``` -->

```{r echo=FALSE, comment=""}
htmltools::h3(outcome)
models <- variable_effect(data_set, outcome, outcomes_2y[[outcome]], demographics)
htmltools::h5('Demographics')
models$demographic %>% print
htmltools::h5('Radiology')
models$radiology %>% print
```



```{r echo=FALSE}
outcome <- outcomes[4]
htmltools::h1(outcome)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}

data_set[, 
  .SD, 
  .SDcols=c(get_base_outcome(outcome, first_visit=TRUE), outcomes_2y[[outcome]], outcome)
] %>% 
  melt() %>% 
  ggplot(aes(variable, value)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 10, vjust = 0.5, hjust=1))
```

<!-- ```{r echo=FALSE, include=FALSE} -->
<!-- demo_plots <- plot_scores(data_set, outcome, demographics_all) -->
<!-- ``` -->


<!-- ```{r echo=FALSE, message=FALSE, fig.height=30, fig.width=10, warning=FALSE} -->
<!-- do.call("grid.arrange", c(demo_plots, ncol=ncols_plots)) -->
<!-- ``` -->

```{r echo=FALSE, comment=""}
htmltools::h3(outcome)
models <- variable_effect(data_set, outcome, outcomes_2y[[outcome]], demographics)
htmltools::h5('Demographics')
models$demographic %>% print
htmltools::h5('Radiology')
models$radiology %>% print
```


```{r echo=FALSE}
outcome <- outcomes[5]
htmltools::h1(outcome)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}

data_set[, 
  .SD, 
  .SDcols=c(get_base_outcome(outcome, first_visit=TRUE), outcomes_2y[[outcome]], outcome)
] %>% 
  melt() %>% 
  ggplot(aes(variable, value)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 10, vjust = 0.5, hjust=1))
```

<!-- ```{r echo=FALSE, include=FALSE} -->
<!-- demo_plots <- plot_scores(data_set, outcome, demographics_all) -->
<!-- ``` -->


<!-- ```{r echo=FALSE, message=FALSE, fig.height=30, fig.width=10, warning=FALSE} -->
<!-- do.call("grid.arrange", c(demo_plots, ncol=ncols_plots)) -->
<!-- ``` -->

```{r echo=FALSE, comment=""}
htmltools::h3(outcome)
models <- variable_effect(data_set, outcome, outcomes_2y[[outcome]], demographics)
htmltools::h5('Demographics')
models$demographic %>% print
htmltools::h5('Radiology')
models$radiology %>% print
```
