---
title: "Descriptive Stats"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
# knitr::opts_knit$set(root.dir = '../')
knitr::opts_knit$set(
  echo = FALSE, 
  root.dir=normalizePath('../'),
  warning=FALSE, 
  comment="",
  message=FALSE
)
```


```{r echo=FALSE, warning=FALSE, include=FALSE}
library(readxl)
library(data.table)
library(magrittr)
library(yaml)
library(glue)
source('five_years_depuy_review/helpers.R')
source('basic.R')
f <- glue

vars <- read_yaml('five_years_depuy_review/descriptive.yml')
vars$surgery <- c(vars$surgery, 'uiv_t10_12_l1')
```


```{r echo=FALSE, warning=FALSE, include=FALSE}
xls_path <- '../../data/ESSG Extraction_DEC_OP_ NON DePuy v7.xlsx'

clinical_data_0 <- read_excel(xls_path) %>% 
  as.data.table()
clinical_data_0 <- clean_data(clinical_data_0)
```


```{r echo=FALSE, warning=FALSE, include=FALSE}
xls_path <- '../../data/ESSG extraction DEC 2022_4th report 5Y - ONLY DPS Mod.xlsx'

clinical_data_1 <- read_excel(xls_path) %>% 
  as.data.table()
clinical_data_1 <- clean_data(clinical_data_1)
```

```{r}
years_rad <- sapply(c("6W.", "2Y.", "5Y."), function(x) paste(x, vars$radiology), simplify = TRUE)
years_quality <- sapply(c("6M.", "2Y.", "5Y."), function(x) paste(x, vars$quality), simplify = TRUE)
quality_first <- paste(vars$quality, "_First Visit", sep="")

all_vars <- c(
  unlist(vars[c("demographics", "radiology", "surgery")]) %>% unique,
  '2 YEAR VISIT - Date of visit',
  '3 YEAR VISIT - Date of visit',
  '5 YEAR VISIT - Date of visit',
  '6 YEAR VISIT - Date of visit',
  'Code of the patient', 
  'st1. Date of Stage',
  years_rad, 
  years_quality,
  quality_first
)
  
clinical_data <- rbind(
  clinical_data_0[, .SD, .SDcols=all_vars][, type:='non-depuy'],
  clinical_data_1[, .SD, .SDcols=all_vars][, type:='depuy']
)
```

### Filters
```{r warning=FALSE }
discarded_patients <- readLines('five_years/discarded_patients')

clinical_data %<>% 
  .[, followup_2y := 
      !is.na(`2 YEAR VISIT - Date of visit`) | 
      !is.na(`3 YEAR VISIT - Date of visit`)] %>% 
  .[, followup_5y := 
      !is.na(`5 YEAR VISIT - Date of visit`) | 
      !is.na(`6 YEAR VISIT - Date of visit`)]
```


- Number of Patients
```{r, comment=""}
clinical_data[, .(total=`Code of the patient` %>% uniqueN), type]
```

- Number of patients with visit in 2 years
```{r, comment=""}
clinical_data[followup_2y==TRUE, .(total=`Code of the patient` %>% uniqueN), type]
```

- Number of patients with visit in 5 years
```{r, comment=""}
clinical_data[followup_5y==TRUE, .(total=`Code of the patient` %>% uniqueN), type]
```



```{r echo=TRUE}
# clinical_data %<>%
#   .[followup_2y==TRUE] %>%
#   .[`st1. Date of Stage` %>% as.Date() < as.Date('2016-6-1')]
```

Total Patients for the analysis
```{r, comment="", warning=FALSE}
clinical_data[, .(total=`Code of the patient` %>% uniqueN), type]
```

### Demographics
```{r echo=FALSE, comment="", warning=FALSE}
for(var_ in vars$demographics ){
  cat(var_)
  cat('\n')
  res <- stats_fun(clinical_data, var_)
  for( res_name in names(res) ){
    print(res_name)
    print(res[[res_name]])
  }
  cat('\n\n')
}
```


### Radiology
```{r echo=FALSE, comment="", warning=FALSE}
dt <- clinical_data %>% copy

for(var_ in vars$radiology ){
  var_6w <- "6W. {var_}" %>% f
  var_2y <- "2Y. {var_}" %>% f
  var_5y <- "5Y. {var_}" %>% f
  vars_years <- c(var_, var_6w, var_2y, var_5y)
  for(var_y in vars_years){
    cat(var_y)
    cat('\n')
    res <- stats_fun(dt, var_y)
    for( res_name in names(res) ){
      print(res_name)
      print(res[[res_name]])
    }
    cat('\n\n')
    
    if(var_y != var_){
      var_y_gain <- "{var_y}_gain" %>% f
      dt[, c(var_y_gain) := get(var_y) - get(var_)]
      
      cat(var_y_gain)
      cat('\n')
      res <- stats_fun(dt, var_y_gain)
      for( res_name in names(res) ){
        print(res_name)
        print(res[[res_name]])
      }
      cat('\n\n')
    }
  }


  cat('{var_} tests\n' %>% f)
  rad_ <- clinical_data[[var_]]
  rad_6w <- clinical_data[[var_6w]]
  rad_2y <- clinical_data[[var_2y]]
  rad_5y <- clinical_data[[var_5y]]
  cat('\npreop vs 6w p-value\n')
  cat(t.test(rad_, rad_6w)$p.val)
  cat('\n6w vs 2y p-value\n')
  cat(t.test(rad_6w, rad_2y)$p.val)
  cat('\n')
  cat('\n6w vs 5y p-value\n')
  cat(t.test(rad_6w, rad_5y)$p.val)
  cat('\n')
  cat('2y vs 5y p-value\n')
  cat(t.test(rad_2y, rad_5y)$p.val)
  cat('\n\n')
}
```


### Quality of Life
```{r echo=FALSE, comment="", warning=FALSE}
dt <- clinical_data %>% copy

for(var_0 in vars$quality ){
  var_ <- "{var_0}_First Visit" %>% f
  var_6m <- "6M. {var_0}" %>% f
  var_2y <- "2Y. {var_0}" %>% f
  var_5y <- "5Y. {var_0}" %>% f
  vars_years <- c(var_, var_6m, var_2y, var_5y)
  for(var_y in vars_years){
    cat(var_y)
    cat('\n')
    res <- stats_fun(clinical_data, var_y)
    for( res_name in names(res) ){
      print(res_name)
      print(res[[res_name]])
    }
    cat('\n\n')
    
    if(var_y != var_){
      var_y_gain <- "{var_y}_gain" %>% f
      dt[, c(var_y_gain) := get(var_y) - get(var_)]
      
      cat(var_y_gain)
      cat('\n')
      res <- stats_fun(dt, var_y_gain)
      for( res_name in names(res) ){
        print(res_name)
        print(res[[res_name]])
      }
      cat('\n\n')
    }
  }

  cat('{var_} tests\n' %>% f)
  hrqol_ <- clinical_data[[var_]]
  hrqol_6m <- clinical_data[[var_6m]]
  hrqol_2y <- clinical_data[[var_2y]]
  hrqol_5y <- clinical_data[[var_5y]]
  cat('\npreop vs 6m p-value\n')
  cat(t.test(hrqol_, hrqol_6m)$p.val)
  cat('\n6m vs 2y p-value\n')
  cat(t.test(hrqol_6m, hrqol_2y)$p.val)
  cat('\n')
  cat('\n6m vs 5y p-value\n')
  cat(t.test(hrqol_6m, hrqol_5y)$p.val)
  cat('\n')
  cat('2y vs 5y p-value\n')
  cat(t.test(hrqol_2y, hrqol_5y)$p.val)
  cat('\n\n')
}
```


### Surgery
```{r echo=FALSE, comment="", warning=FALSE}
for(var_ in vars$surgery ){
  cat(var_)
  cat('\n')
  res <- stats_fun(clinical_data, var_)
  for( res_name in names(res) ){
    print(res_name)
    print(res[[res_name]])
  }
  cat('\n\n')
}
```
