---
title: "Reinterventions exploration"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_knit$set(
  echo = FALSE, 
  warning = FALSE,
  root.dir=normalizePath('../../')
)
```

```{r warning=FALSE, include=FALSE}
library(readxl)
library(magrittr)
library(data.table)
library(stringr)
library(yaml)
library(zeallot)

source('code/basic.R')
source('code/utils.R')
source('code/reintervention/reinterventions-util.R')

c(time_evolution, complications, category_los, clinical_data) %<-% get_data()

```


# Hospitalization Time

```{r warning=FALSE, echo=FALSE, fig.height=4}
time_evolution %>% 
  ggplot(aes(reintervention, hospitalization_time)) +
  geom_boxplot() +
  ylim(c(0, 250))

time_evolution[, 
  quantile(hospitalization_time, na.rm=TRUE) %>% as.list, 
  reintervention]
```

# Proportion of reinterventions

```{r warning=FALSE, echo=FALSE, fig.height=3.5}

total_patients <- time_evolution[, uniqueN(patient_id)]

time_evolution %>% 
  .[, .(N=.N/total_patients), reintervention] %>% 
  ggplot(aes(reintervention, N, group=1)) +
  geom_line() +
  geom_text(aes(label=round(N*100, 1))) +
  ggtitle('Proportion of patients, total {total_patients}' %>% f) +
  ylab('%') +
  xlab('Reintervention')
```

# Proportion of SICU transfers

```{r warning=FALSE, echo=FALSE, fig.height=3.5}
time_evolution %>% 
  .[, .(condition=(sicu_transferred == 'Yes'), reintervention)] %>% 
  plot_evolution('transferred to SICU')
```


# Evolution of surgeries

```{r warning=FALSE, echo=FALSE, fig.height=4}


time_evolution %>% 
  .[, .(condition=co3==1, reintervention)] %>% 
  plot_evolution('3CO')

time_evolution %>% 
  .[, .(condition=(`Implant removal` == 'Yes'), reintervention)] %>% 
  plot_evolution('Implant removal')

time_evolution %>% 
  .[, .(condition=(`Infection debridement` == 'Yes'), reintervention)] %>% 
  plot_evolution('Infection Debridement')

time_evolution %>% 
  .[, .(condition=(`Anterior Instrumented Fusion` == 'Yes'), reintervention)] %>% 
  plot_evolution('Anterior Instrumented Fusion')

time_evolution %>% 
  .[, .(condition=(`Posterior Instrumented Fusion` == 'Yes'), reintervention)] %>% 
  plot_evolution('Posterior Instrumented Fusion')

time_evolution %>% 
  .[, .(condition=(`Decompression` == 'Yes'), reintervention)] %>% 
  plot_evolution('Decompression')

time_evolution %>% 
  .[, .(condition=(`Interbody Fusion` == 'Yes'), reintervention)] %>% 
  plot_evolution('Interbody Fusion')

time_evolution %>% 
  .[, .(condition=(`Osteotomy` == 'Yes'), reintervention)] %>% 
  plot_evolution('Osteotomy')

time_evolution %>% 
  .[, .(condition=(`Rod change` == 'Yes'), reintervention)] %>% 
  plot_evolution('Rod change')

time_evolution %>% 
  .[, .(condition=(`Scar revision` == 'Yes'), reintervention)] %>% 
  plot_evolution('Scar revision')
```


```{r echo=FALSE}
time_evolution %>% 
  ggplot(aes(blood_loss, fill=reintervention, color=reintervention)) +
  geom_density(alpha=0.1) +
  ggtitle('Blood Loss') +
  xlim(c(0, 3000 ))+
  facet_grid(reintervention~.)

time_evolution %>% 
  ggplot(aes(reintervention, blood_loss)) +
  geom_boxplot() +
  ggtitle('Blood Loss')


time_evolution %>% 
  ggplot(aes(surgical_time, fill=reintervention, color=reintervention)) +
  geom_density(alpha=0.1) +
  ggtitle('Surgical Time') +
  xlim(c(0, 1000 ))+
  facet_grid(reintervention~.)

time_evolution %>% 
  ggplot(aes(reintervention, surgical_time)) +
  geom_boxplot() +
  ggtitle('Surgical Time')
```

