---
title: "Reinterventions exploration"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_knit$set(
  echo = FALSE, 
  warning = FALSE,
  root.dir=normalizePath('../../')
)
```

```{r warning=FALSE, include=FALSE}
library(readxl)
library(magrittr)
library(data.table)
library(stringr)
library(yaml)
library(GGally)

source('code/basic.R')
source('code/utils.R')

xls_path <- 'data/ESSG extraction July 2020_2.xlsx'
# excel_sheets(xls_path)

vars_ <- read_yaml('code/reintervention/treatment_vars.yml')

rev_patient_data <- read_excel(xls_path, sheet = "Rev surgeries") %>% 
  data.table 
clinical_data <- read_excel(xls_path) %>% 
  data.table() 

rev_patient_data %>% 
  .[, `Code of the patient`] %>% 
  unique -> rev_patients

# clinical_data %>% 
#   .[, .SD, .SDcols=c('Code of the patient', vars_ %>% unlist)] %>% 
#   .[, `Rev Surgery` := ifelse(`Code of the patient` %chin% rev_patients, 'Yes', 'No')] %>% 
#   .[, `Code of the patient` := NULL] %>% 
#   clean_names_dt %>% 
#   .[, co3 := 0] %>% 
#   .[schwab_type_3_number + schwab_type_4_number + schwab_type_5_number > 0, co3 := 1] %>% 
#   .[, schwab_type_3_number := NULL] %>% 
#   .[, schwab_type_4_number := NULL] %>% 
#   .[, schwab_type_5_number := NULL] %>% 
#   .[, pelvic_fixation := 0] %>% 
#   .[grepl('Iliac', posterior_instrumented_fusion_upper_lower_levels, fixed=TRUE), 
#     pelvic_fixation := 1] %>% 
#   .[, posterior_instrumented_fusion_upper_lower_levels:=NULL] ->
#   data_
# 
# vars_$outcomes %<>% c('rev_surgery')

rev_patient_data[, .(
  patient_id=`Code of the patient`, 
  stage_date=`st1. Date of Stage 1`,
  surgical_time=`Total surgical time st1+st2+st3`,
  blood_loss=`Total blood loss (mL)`)] ->
  time_evolution

clinical_data[
  `Code of the patient` %chin% rev_patients, .(
  patient_id=`Code of the patient`, 
  stage_date=`st1. Date of Stage 1`,
  surgical_time=`Total surgical time st1+st2+st3`,
  blood_loss= `Total blood loss (mL) st1+st2+st3`)] %>% 
  rbind(time_evolution) ->
  time_evolution

time_evolution %<>% 
  .[!is.na(stage_date)] %>% 
  .[, diff_years:=difftime(stage_date, min(stage_date), units = "days")/365, patient_id] %>% 
  setorder(patient_id, diff_years) %>% 
  .[, reintervention:=factor(1:.N), patient_id]

max_reinterventions <- time_evolution[, max(reintervention %>% as.character %>% as.numeric)]
```

```{r warning=FALSE, echo=FALSE, comment=""}
# cat(vars_ %>% as.yaml)
```


# Time of Reinterventions

```{r warning=FALSE, echo=FALSE, fig.height=4}

max_years <- time_evolution[, max(diff_years)]

time_evolution %>% 
  .[reintervention %in% 2:max_reinterventions] %>% 
  ggplot(aes(diff_years,  fill=reintervention, color=reintervention)) +
  geom_density(alpha=0.1) +
  xlim(c(0, max_years)) +
  ggtitle('Time of reinterventions') ->
  data_plot
print(data_plot)
```

# Total blood loss of reinterventions

```{r warning=FALSE, echo=FALSE, fig.height=3.5}
max_blood_loss <- time_evolution[, blood_loss %>% na.omit %>% max]

title <- 'Total blood loss distribution'

time_evolution %>% 
  .[reintervention %in% 2:max_reinterventions] %>%
  ggplot(aes(blood_loss)) +
  geom_density() +
  xlim(c(0, max_blood_loss)) +
  ggtitle(title) ->
  data_plot
print(data_plot)
```

# Blood loss of reinterventions

```{r warning=FALSE, echo=FALSE, fig.height=3.5}
time_evolution %>% 
  .[reintervention %in% 2:max_reinterventions] %>%
  ggplot(aes(blood_loss, fill=reintervention, color=reintervention))+
  geom_density(alpha = 0.1) +
  xlim(c(0, max_blood_loss)) +
  ggtitle('Total blood loss distribution') ->
  data_plot
print(data_plot)
```


# Total surgical time of reinterventions

```{r warning=FALSE, echo=FALSE, fig.height=4}
max_surgical_time <- time_evolution[, surgical_time %>% na.omit %>% max]

time_evolution %>% 
  .[reintervention %in% 2:max_reinterventions] %>%
  ggplot(aes(surgical_time)) +
  geom_density() +
  xlim(c(0, max_surgical_time)) +
  ggtitle('Total surgical time distribution') ->
  data_plot
print(data_plot)
```


```{r warning=FALSE, echo=FALSE, fig.height=4}
time_evolution %>% 
  .[reintervention %in% 2:max_reinterventions] %>%
  ggplot(aes(surgical_time, fill=reintervention, color=reintervention)) +
  geom_density(alpha=0.1) +
  xlim(c(0, max_surgical_time)) +
  ggtitle('Total surgical time distribution') ->
  data_plot
print(data_plot)
```