---
title: "Reinterventions exploration"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_knit$set(
  echo = FALSE, 
  warning = FALSE,
  root.dir=normalizePath('../../')
)
```

```{r warning=FALSE, include=FALSE}
library(readxl)
library(magrittr)
library(data.table)
library(stringr)
library(yaml)
library(zeallot)

source('code/basic.R')
source('code/utils.R')
source('code/reintervention/reinterventions-util.R')

c(time_evolution, complications, category_los, clinical_data) %<-% get_data()

```


# Quality life increment for reinterventions

```{r echo=FALSE, include=FALSE}
lapply(1:6, function(y_){
  odi <- "{y_}Y. ODI - Score (%)" %>% f
  odi_base <- odi %>% get_base_outcome(first_visit=TRUE)
  srss <- "{y_}Y. SRS22 - SRS Subtotal score" %>% f
  srss_base <- srss %>% get_base_outcome(first_visit=TRUE)
  mcs <- "{y_}Y. SF36 - MCS" %>% f
  mcs_base <- mcs %>% get_base_outcome(first_visit=TRUE)
  pcs <- "{y_}Y. SF36 - PCS" %>% f
  pcs_base <- pcs %>% get_base_outcome(first_visit=TRUE)
  
  clinical_data[, .(
    odi=get(odi) - get(odi_base), 
    srss=get(srss) - get(srss_base), 
    mcs=get(mcs) - get(mcs_base), 
    pcs=get(pcs) - get(pcs_base),
    patient_id=`Code of the patient`)] ->
    patient_quality
  
  time_evolution %>% 
    .[diff_years < y_, ] %>% 
    .[, .(last_operation= max(diff_years)), .(patient_id)] %>% 
    .[, last_operation := as.numeric(last_operation)] %>% 
    merge(patient_quality, by='patient_id') %>% 
    .[, outcome_year:=y_] ->
    res
  
  get_lm_info <- function(data_, name){
    "{name}~last_operation" %>% f %>% as.formula() %>% 
    lm(data=data_) %>% summary %>% .$coefficients %>% 
      .[2, c(1, 2)] %>% round(1) -> lm_info
    
    "{lm_info[1]}\n({lm_info[2]})" %>% f
  }
  
  res %>% 
    .[, odi_info:=get_lm_info(.SD, 'odi')] %>% 
    .[, srss_info:=get_lm_info(.SD, 'srss')] %>% 
    .[, mcs_info:=get_lm_info(.SD, 'mcs')] %>% 
    .[, pcs_info:=get_lm_info(.SD, 'pcs')]
  
  return(res)
}) %>% 
  do.call(rbind, .) -> 
  res
```


```{r echo=FALSE, warning=FALSE}
info.labs <- res[, .(info=unique(odi_info)), .(outcome_year)]
outcome_year.labs <- info.labs[, info]
names(outcome_year.labs) <- info.labs[, outcome_year]

res %>% 
  ggplot(aes(last_operation, odi)) +
  geom_point() +
  geom_jitter(width=0.005) +
  ggtitle('ODI Score increment') +
  geom_smooth(method='lm') +
  facet_grid(outcome_year~., 
    labeller=labeller(outcome_year=outcome_year.labs))
```


```{r echo=FALSE, warning=FALSE}
info.labs <- res[, .(info=unique(srss_info)), .(outcome_year)]
outcome_year.labs <- info.labs[, info]
names(outcome_year.labs) <- info.labs[, outcome_year]

res %>% 
  ggplot(aes(last_operation, srss)) +
  geom_point() +
  geom_jitter(width=0.005) +
  geom_smooth(method='lm') +
  ggtitle('SRS22 Subtotal increment') +
  facet_grid(outcome_year~., 
    labeller=labeller(outcome_year=outcome_year.labs))
```


```{r echo=FALSE, warning=FALSE}
info.labs <- res[, .(info=unique(mcs_info)), .(outcome_year)]
outcome_year.labs <- info.labs[, info]
names(outcome_year.labs) <- info.labs[, outcome_year]

res %>% 
  ggplot(aes(last_operation, mcs)) +
  geom_point() +
  geom_jitter(width=0.005) +
  geom_smooth(method='lm') +
  ggtitle('SF36 - MCS increment') +
  facet_grid(outcome_year~., 
    labeller=labeller(outcome_year=outcome_year.labs))
```

```{r echo=FALSE, warning=FALSE}
info.labs <- res[, .(info=unique(pcs_info)), .(outcome_year)]
outcome_year.labs <- info.labs[, info]
names(outcome_year.labs) <- info.labs[, outcome_year]

res %>% 
  ggplot(aes(last_operation, pcs)) +
  geom_point() +
  geom_jitter(width=0.005) +
  geom_smooth(method='lm') +
  ggtitle('SF36 - MCS increment') +
  facet_grid(outcome_year~., 
    labeller=labeller(outcome_year=outcome_year.labs))
```

### Had Intervention

For each outcome year, whether the pacient had an intervention before the questionaire
```{r echo=FALSE, warning=FALSE}
res %>% 
  ggplot(aes(last_operation, pcs)) +
  geom_point() +
  geom_jitter(width=0.005) +
  geom_smooth(method='lm') +
  ggtitle('SF36 - PCS increment') +
  facet_grid(outcome_year~.)
```

```{r echo=FALSE, warning=FALSE}
lapply(1:6, function(y_){
  odi <- "{y_}Y. ODI - Score (%)" %>% f
  odi_base <- odi %>% get_base_outcome(first_visit=TRUE)
  srss <- "{y_}Y. SRS22 - SRS Subtotal score" %>% f
  srss_base <- srss %>% get_base_outcome(first_visit=TRUE)
  mcs <- "{y_}Y. SF36 - MCS" %>% f
  mcs_base <- mcs %>% get_base_outcome(first_visit=TRUE)
  pcs <- "{y_}Y. SF36 - PCS" %>% f
  pcs_base <- pcs %>% get_base_outcome(first_visit=TRUE)
  
  clinical_data[, .(
    odi=get(odi) - get(odi_base), 
    srss=get(srss) - get(srss_base), 
    mcs=get(mcs) - get(mcs_base), 
    pcs=get(pcs) - get(pcs_base),
    patient_id=`Code of the patient`)] ->
    patient_quality
  
  time_evolution %>% 
    .[diff_years < y_, ] %>% 
    .[, reint_num:=as.numeric(as.character(reintervention))] %>% 
    .[, had_reintervention := max(reint_num) > 0, patient_id] %>% 
    merge(patient_quality, by='patient_id') %>% 
    .[, outcome_year:=factor(y_)] ->
    res
  
  return(res)
}) %>% 
  do.call(rbind, .) -> 
  res
```


```{r echo=FALSE}
res %>% 
  ggplot(aes(outcome_year, odi, fill=had_reintervention)) +
  geom_boxplot(position = "dodge2") +
  ggtitle('ODI Score increment')
```


```{r echo=FALSE}
res %>% 
  ggplot(aes(outcome_year, srss, fill=had_reintervention)) +
  geom_boxplot(position = "dodge2") +
  ggtitle('SRS22 Subtotal increment')
```


```{r echo=FALSE}
res %>% 
  ggplot(aes(outcome_year, mcs, fill=had_reintervention)) +
  geom_boxplot(position = "dodge2") +
  ggtitle('SF36 - MCS increment')
```


```{r echo=FALSE}
res %>% 
  ggplot(aes(outcome_year, pcs, fill=had_reintervention)) +
  geom_boxplot(position = "dodge2") +
  ggtitle('SF36 - PCS increment') 
```


# Had intervention evolution

```{r echo=FALSE}
lapply(1:6, function(y_){
  odi <- "{y_}Y. ODI - Score (%)" %>% f
  odi_base <- odi %>% get_base_outcome(first_visit=TRUE)
  srss <- "{y_}Y. SRS22 - SRS Subtotal score" %>% f
  srss_base <- srss %>% get_base_outcome(first_visit=TRUE)
  mcs <- "{y_}Y. SF36 - MCS" %>% f
  mcs_base <- mcs %>% get_base_outcome(first_visit=TRUE)
  pcs <- "{y_}Y. SF36 - PCS" %>% f
  pcs_base <- pcs %>% get_base_outcome(first_visit=TRUE)
  
  clinical_data[, .(
    odi=get(odi) - get(odi_base), 
    srss=get(srss) - get(srss_base), 
    mcs=get(mcs) - get(mcs_base), 
    pcs=get(pcs) - get(pcs_base),
    patient_id=`Code of the patient`)] ->
    patient_quality
  
  time_evolution %>% 
    .[diff_years < y_, ] %>% 
    .[, sel_year:=y_] %>% 
    .[, reint_num:=as.numeric(as.character(reintervention))] %>% 
    .[, had_reintervention := max(reint_num) > 0, patient_id] %>% 
    merge(patient_quality, by='patient_id') %>% 
    .[, outcome_year:=factor(y_)] ->
    res
  
  return(res)
}) %>% 
  do.call(rbind, .) -> 
  res
```

Black lines are the mean value of the score

```{r echo=FALSE}
mean_val <- res[, mean(odi %>% na.omit)]
ggplot(res, aes(sel_year, odi, color=had_reintervention)) +
  geom_point() +
  geom_smooth(method='lm') +
  geom_abline(slope=0, intercept = mean_val, color='black') +
  ggtitle('ODI Score increment')
```


```{r echo=FALSE}
mean_val <- res[, mean(srss %>% na.omit)]
ggplot(res, aes(sel_year, srss, color=had_reintervention)) +
  geom_point() +
  geom_smooth(method='lm') +
  geom_abline(slope=0, intercept = mean_val, color='black') +
  ggtitle('SRS22 Subtotal increment')
```

```{r echo=FALSE}
mean_val <- res[, mean(mcs %>% na.omit)]
ggplot(res, aes(sel_year, mcs, color=had_reintervention)) +
  geom_point() +
  geom_smooth(method='lm') +
  geom_abline(slope=0, intercept = mean_val, color='black') +
  ggtitle('SF36 - MCS increment')
```

```{r echo=FALSE}
mean_val <- res[, mean(pcs %>% na.omit)]
ggplot(res, aes(sel_year, pcs, color=had_reintervention)) +
  geom_point() +
  geom_smooth(method='lm') +
  geom_abline(slope=0, intercept = mean_val, color='black') +
  ggtitle('SF36 - PCS increment')
```

