---
title: "Reinterventions exploration"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_knit$set(
  echo = FALSE, 
  warning = FALSE,
  root.dir=normalizePath('../../')
)
```

```{r warning=FALSE, include=FALSE}
library(readxl)
library(magrittr)
library(data.table)
library(stringr)
library(yaml)
library(GGally)

source('code/basic.R')
source('code/utils.R')

xls_path <- 'data/ESSG extraction July 2020_3.xlsx'
# excel_sheets(xls_path)

vars_ <- read_yaml('code/reintervention/treatment_vars.yml')

rev_patient_data <- read_excel(xls_path, sheet = "Rev surgeries") %>% 
  data.table 
clinical_data <- read_excel(xls_path) %>% 
  data.table() 
complications <- read_excel(xls_path, sheet = "Complications") %>% 
  data.table 

rev_patient_data %>% 
  .[, `Number of Schwab Type 3` := `Number of Schwab Type 3` %>%  as.numeric] %>% 
  .[, `Number of Schwab Type 4` := `Number of Schwab Type 4` %>%  as.numeric] %>% 
  .[, `Number of Schwab Type 5` := `Number of Schwab Type 5` %>%  as.numeric] %>% 
  .[, co3 := 0] %>% 
  .[`Number of Schwab Type 3` + `Number of Schwab Type 4` + `Number of Schwab Type 5` > 0, co3 := 1] %>% 
  .[, .(
    patient_id=`Code of the patient`, 
    stage_date=`st1. Date of Stage 1`,
    surgical_time=`Total surgical time st1+st2+st3`,
    blood_loss=`Total blood loss (mL)`,
    hospitalization_time=`Hospitalization time`,
    sicu_transferred=`Patient transferred to SICU post op`,
    sicu_los=`SICU length of stay`,
    co3,
    `Infection debridement`,
    `Implant removal`,
    `Anterior Instrumented Fusion`,
    `Number of Anterior Instrumented Levels`,
    `Posterior Instrumented Fusion`,
    `Number of Posterior Instrumented Levels`,
    `Decompression`,
    `Number of decompressions`,
    `Interbody Fusion`,
    `Number of Interbody Fusions`,
    `Osteotomy`,
    `Rod change`,
    `Scar revision`
  )] %>% 
  .[, hospitalization_time:=gsub(' days', '', hospitalization_time) %>% as.numeric]->
  time_evolution

clinical_data %>% 
  .[, co3 := 0] %>% 
  .[`Schwab Type 3: Number` + `Schwab Type 4: Number` + `Schwab Type 5: Number` > 0, co3 := 1] %>% 
  .[, .(
    patient_id=`Code of the patient`, 
    stage_date=`st1. Date of Stage 1`,
    surgical_time=`Total surgical time st1+st2+st3`,
    blood_loss= `Total blood loss (mL) st1+st2+st3`,
    hospitalization_time=`Hospitalization time`,
    sicu_transferred=`Patient transferred to SICU post op`,
    sicu_los=`SICU length of stay`,
    co3,
    `Infection debridement`,
    `Implant removal`,
    `Anterior Instrumented Fusion`,
    `Number of Anterior Instrumented Levels`,
    `Posterior Instrumented Fusion`,
    `Number of Posterior Instrumented Levels`,
    `Decompression`,
    `Number of decompressions`,
    `Interbody Fusion`,
    `Number of Interbody Fusions`,
    `Osteotomy`,
    `Rod change`,
    `Scar revision`
  )] %>% 
  rbind(time_evolution) ->
  time_evolution

time_evolution %<>% 
  .[is.na(sicu_los) & is.na(sicu_transferred), sicu_transferred:='No'] %>% 
  .[!is.na(stage_date)] %>% 
  .[, diff_years:=difftime(stage_date, min(stage_date), units = "days")/365, patient_id] %>% 
  setorder(patient_id, diff_years) %>% 
  .[, reintervention:=factor(0:(.N-1)), patient_id]
```

```{r warning=FALSE, echo=FALSE, comment="", include=FALSE}
plot_evolution <- function(dt, value_title=''){
  dt %>% 
    .[, .(
      prop=mean(condition),
      N=.N),
      reintervention] %>% 
    .[, ci:=1.96*sqrt(prop*(1-prop)/N)] ->
    res
  res %>% 
    .[, ymin:=max(prop-ci, 0), 1:nrow(res)] %>% 
    .[, ymax:=min(prop+ci, 1), 1:nrow(res)] %>% 
    ggplot(aes(reintervention, y=prop, group=1)) +
    geom_line() +
    geom_ribbon(
      aes(ymin=ymin, ymax=ymax), 
      linetype=2, alpha=0.1) +
    ggtitle('Proportion of {value_title}' %>% f) +
    ylab('%') +
    ylim(c(-0.001, 1.001)) +
    xlab('Reintervention') ->
  res_plot

  return(res_plot)
}
```


# Hospitalization Time

```{r warning=FALSE, echo=FALSE, fig.height=4}
time_evolution %>% 
  ggplot(aes(reintervention, hospitalization_time)) +
  geom_boxplot() +
  ylim(c(0, 250))

time_evolution[, 
  quantile(hospitalization_time, na.rm=TRUE) %>% as.list, 
  reintervention]
```

# Proportion of reinterventions

```{r warning=FALSE, echo=FALSE, fig.height=3.5}

total_patients <- time_evolution[, uniqueN(patient_id)]

time_evolution %>% 
  .[, .(N=.N/total_patients), reintervention] %>% 
  ggplot(aes(reintervention, N, group=1)) +
  geom_line() +
  geom_text(aes(label=round(N*100, 1))) +
  ggtitle('Proportion of patients, total {total_patients}' %>% f) +
  ylab('%') +
  xlab('Reintervention')
```

# Proportion of SICU transfers

```{r warning=FALSE, echo=FALSE, fig.height=3.5}
time_evolution %>% 
  .[, .(condition=(sicu_transferred == 'Yes'), reintervention)] %>% 
  plot_evolution('transferred to SICU')
```


# Evolution of surgeries

```{r warning=FALSE, echo=FALSE, fig.height=4}


time_evolution %>% 
  .[, .(condition=co3==1, reintervention)] %>% 
  plot_evolution('3CO')

time_evolution %>% 
  .[, .(condition=(`Implant removal` == 'Yes'), reintervention)] %>% 
  plot_evolution('Implant removal')

time_evolution %>% 
  .[, .(condition=(`Infection debridement` == 'Yes'), reintervention)] %>% 
  plot_evolution('Infection Debridement')

time_evolution %>% 
  .[, .(condition=(`Anterior Instrumented Fusion` == 'Yes'), reintervention)] %>% 
  plot_evolution('Anterior Instrumented Fusion')

time_evolution %>% 
  .[, .(condition=(`Posterior Instrumented Fusion` == 'Yes'), reintervention)] %>% 
  plot_evolution('Posterior Instrumented Fusion')

time_evolution %>% 
  .[, .(condition=(`Decompression` == 'Yes'), reintervention)] %>% 
  plot_evolution('Decompression')

time_evolution %>% 
  .[, .(condition=(`Interbody Fusion` == 'Yes'), reintervention)] %>% 
  plot_evolution('Interbody Fusion')

time_evolution %>% 
  .[, .(condition=(`Osteotomy` == 'Yes'), reintervention)] %>% 
  plot_evolution('Osteotomy')

time_evolution %>% 
  .[, .(condition=(`Rod change` == 'Yes'), reintervention)] %>% 
  plot_evolution('Rod change')

time_evolution %>% 
  .[, .(condition=(`Scar revision` == 'Yes'), reintervention)] %>% 
  plot_evolution('Scar revision')
```


```{r echo=FALSE}
time_evolution %>% 
  ggplot(aes(blood_loss, fill=reintervention, color=reintervention)) +
  geom_density(alpha=0.1) +
  ggtitle('Blood Loss') +
  xlim(c(0, 3000 ))+
  facet_grid(reintervention~.)

time_evolution %>% 
  ggplot(aes(reintervention, blood_loss)) +
  geom_boxplot() +
  ggtitle('Blood Loss')


time_evolution %>% 
  ggplot(aes(surgical_time, fill=reintervention, color=reintervention)) +
  geom_density(alpha=0.1) +
  ggtitle('Surgical Time') +
  xlim(c(0, 1000 ))+
  facet_grid(reintervention~.)

time_evolution %>% 
  ggplot(aes(reintervention, surgical_time)) +
  geom_boxplot() +
  ggtitle('Blood Loss')
```



# Complications

```{r echo=TRUE}
complications %>% 
  .[`Complication Type`=='Primary'] %>%
  .[`Reoperation Due to Complication`=='Yes'] ->
  complications_
```


```{r warning=FALSE, echo=FALSE, fig.height=4}
calc_reintervention <- function(days_since_surgery){
  days_since_surgery %>% 
      unique %>% 
      sort %>% 
      data.table(days=., position=1:length(.)) %>% 
      merge(data.table(days=days_since_surgery)) %>% 
      .[, position]
}

complications_ %>% 
  .[, .(
    category=`Category of the complication`,
    days_since_surgery=`Days since surgery`,
    patient_id=`Code of the patient`,
    date=`Date of Reoperation`
  )] %>% 
  na.omit %>% 
  setorder(patient_id, days_since_surgery) %>% 
  .[, .(
    category, date, days_since_surgery,
    reintervention=calc_reintervention(days_since_surgery)), 
    patient_id] ->
  complications_

complications_ %>% 
  .[, .N , .(reintervention, category)] %>% 
  ggplot(aes(reintervention, N, group=category, color=category)) +
  geom_line()
```


```{r include=FALSE}
rev_patient_data[, 
  .(patient_id=`Code of the patient`, 
    hospitalization_time=`Hospitalization time`, 
    blood_loss=`Total blood loss (mL)`,
    surgical_time=`Total surgical time st1+st2+st3`,
    date=`st1. Date of Stage 1`)] %>% 
  .[, hospitalization_time:=gsub(' days', '', hospitalization_time) %>% as.numeric] ->
  rev_patient_data_

clinical_data[, .(prior_spine_surgery=`Prior Spine Surgery`),
  .(patient_id=`Code of the patient`)] ->
  prior_surgery

complications_ %>% 
  merge(rev_patient_data_, by=c('patient_id', 'date')) %>% 
  merge(prior_surgery, by='patient_id') ->
  category_los
```

```{r echo=FALSE}
category_los[, 
  .(hospitalization_time=mean(hospitalization_time, na.rm = TRUE), 
    hosp_t_sd=sd(hospitalization_time, na.rm=TRUE)), 
  .(reintervention, category)] %>% 
  .[is.na(hosp_t_sd), hosp_t_sd:=0] ->
  res_

res_[,
  .(hospitalization_time, 
    h_up=hospitalization_time + 1.96*hosp_t_sd,
    h_down=max(hospitalization_time - 1.96*hosp_t_sd, 0),
    reintervention,
    category), 1:nrow(res_)] %>% 
  .[, category := gsub(' ', '\n', category , fixed=TRUE)] %>% 
  ggplot(aes(reintervention, hospitalization_time, group=category, color=category, fill=category)) +
  geom_line() +
  geom_ribbon(
    aes(ymin=h_down, ymax=h_up), 
    linetype=2, alpha=0.1) +
  facet_grid(category~.) +
  ylab('Days') +
  ggtitle('Hospitalization time')
```

```{r echo=FALSE}
category_los %>% .[] %>% 
  # .[, has_mechanical:='Mechanical complications' %in% category,
  .[, is_only_mechanical:=all('Mechanical complications' == category),
    .(patient_id, reintervention)] %>% 
  .[, .(hospitalization_time=mean(hospitalization_time, na.rm = TRUE), 
    hosp_t_sd=sd(hospitalization_time, na.rm=TRUE)), 
  .(reintervention, is_only_mechanical)] %>% 
  .[is.na(hosp_t_sd), hosp_t_sd:=0] ->
  res_

res_[,
  .(hospitalization_time, 
    h_up=hospitalization_time + 1.96*hosp_t_sd,
    h_down=max(hospitalization_time - 1.96*hosp_t_sd, 0),
    reintervention,
    is_only_mechanical), 1:nrow(res_)] %>% 
  ggplot(aes(reintervention, hospitalization_time, group=is_only_mechanical, color=is_only_mechanical, fill=is_only_mechanical)) +
  geom_line() +
  geom_ribbon(
    aes(ymin=h_down, ymax=h_up), 
    linetype=2, alpha=0.1) +
  facet_grid(is_only_mechanical~.) +
  ylab('Days') +
  ggtitle('Hospitalization time for ONLY mechanical interventions')
```

```{r echo=FALSE}
category_los %>% .[] %>% 
  # .[, has_mechanical:='Mechanical complications' %in% category,
  .[, is_only_mechanical:=all('Mechanical complications' == category),
    .(patient_id, reintervention, prior_spine_surgery)] %>% 
  .[, .(hospitalization_time=mean(hospitalization_time, na.rm = TRUE), 
    hosp_t_sd=sd(hospitalization_time, na.rm=TRUE)), 
  .(reintervention, is_only_mechanical, prior_spine_surgery)] %>% 
  .[is.na(hosp_t_sd), hosp_t_sd:=0] ->
  res_

res_[,
  .(hospitalization_time, 
    h_up=hospitalization_time + 1.96*hosp_t_sd,
    h_down=max(hospitalization_time - 1.96*hosp_t_sd, 0),
    reintervention,
    prior_spine_surgery, 
    is_only_mechanical), 1:nrow(res_)] %>% 
  ggplot(aes(reintervention, hospitalization_time, group=prior_spine_surgery, color=prior_spine_surgery, fill=prior_spine_surgery)) +
  geom_line() +
  geom_ribbon(
    aes(ymin=h_down, ymax=h_up), 
    linetype=2, alpha=0.1) +
  facet_grid(is_only_mechanical~.) +
  ylab('Days') +
  ggtitle('Hospitalization time for ONLY mechanical interventions \n with prior spine surgery - differences in means')
```


```{r echo=FALSE}
complication_types <- complications_[, category %>% unique]
lapply(complication_types, function(comp){
  complications_ %>% 
    .[, .(has_category=comp %in% category, category), 
      .(patient_id, reintervention)] %>% 
    .[has_category==TRUE, table(category) %>% as.data.frame, reintervention] %>% 
    data.frame(base_category=comp)
}) %>% 
  do.call(rbind, .) %>% 
  as.data.table %>% 
  .[, base_category := gsub(' ', '\n', base_category , fixed=TRUE)] %>% 
  ggplot(aes(reintervention, Freq, group=category, color=category)) +
  geom_line() +
  geom_point() +
  facet_grid(base_category~.) +
  ggtitle('Complication Category Overlap')
  
  
```

```{r echo=FALSE, warning=FALSE}
complications_[, 
  reintervention_total:=.N, 
  .(reintervention)] %>% 
  .[, .(prop=100*.N/reintervention_total), .(reintervention, category)] %>% 
  ggplot(aes(reintervention, prop, color=category, group=category)) +
  geom_line() +
  ylab('%') +
  ggtitle('Proportion of categories')
```



```{r echo=FALSE, warning=FALSE}
max_reint <- complications_[, max(reintervention)]
complication_types <- complications_[, category %>% unique]
reints <- 1:(max_reint-1)

lapply(complication_types, function(compl1){
  lapply(complication_types, function(compl2){
    sapply(reints, function(reint){
      patient_selection <- complications_[reintervention==reint, .(has_category=compl1 %in% category), .(patient_id)][has_category==TRUE, patient_id]
      base <- complications_[ patient_id %in% patient_selection] 
      denom <- base[reintervention==reint, uniqueN(patient_id)]
      numer <- base[reintervention==(reint + 1) & category==compl2, .N]
      prop <- numer/denom
      c(proportion=prop, ci=1.96*sqrt(prop*(1-prop)/denom))
    }) %>% 
      t %>% 
    data.frame(., reintervention=reints, complication_next=compl2) 
  }) %>% 
    do.call(rbind, .) %>% 
    data.frame(., complication_reintervention=compl1)
}) %>% 
  do.call(rbind, .) %>% 
  data.table  %>% 
  .[, complication_reintervention := gsub(' ', '\n', complication_reintervention , fixed=TRUE)] ->
  res

res %>% 
    .[, ymin:=max(proportion-ci, 0), 1:nrow(res)] %>% 
    .[, ymax:=min(proportion+ci, 1), 1:nrow(res)] %>% 
  ggplot(aes(
    reintervention, proportion, 
    group=complication_next, color=complication_next)
  ) +
  geom_line() +
  geom_point() +
  geom_ribbon(aes(ymin=ymin, ymax=ymax), linetype=2, alpha=0.1) +
  facet_grid(complication_reintervention ~. ) +
  ggtitle('Proportion of complications in next reintervention')

```
