---
title: "L5/Iliac Propensity Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment='', message=FALSE, warning=FALSE)
knitr::opts_knit$set(root.dir = '../')
```


```{r}
library(data.table)
library(magrittr)
library(yaml)
library(kableExtra)
library(pROC)
source('patient_selection.R')
source('liv_l4_l5/utils.R')
source('liv_l4_l5/train.R')

tuneLength <- 8

treatment_name <- 'type'
treatment_vals <- c('Iliac', 'L5')

```

```{r, message=FALSE}
analysis_vars <- read_yaml('descriptive.yml')
vars <- read_yaml('liv_l4_l5/variables.yml')
data_ <- get_data()
```
Initial Patients: `r data_[, .N]`

```{r}
data_ %<>% .[`Posterior Instrumented Fusion` == 'Yes']
 
data_[, `Posterior Instrumented Fusion: Upper / Lower Levels`] %>% 
  sapply(. %>% strsplit('-') %>% .[[1]] %>% .[2]) ->
  post_intr_fusion

data_[post_intr_fusion == 'Iliac', type := 'Iliac']
data_[post_intr_fusion == 'L5', type := 'L5']
data_ %<>% .[!is.na(type)]
```

# Comparability constraints
```{r echo=TRUE}
data_ %<>% 
  .[`Surgical Approach`=='Posterior'] %>% 
  .[`Pelvic Tilt` < 35] %>% 
  .[`Ideal GT` < 21] %>% 
  .[`RLL` > -42] 
```

```{r}
data_[, .N, type]
```


### Confounding Variables

```{r}
confounders <- vars$confounders
# outcomes <- vars$outcomes
vars_ <- c(confounders, treatment_name)
confounders %>% as.yaml %>% cat
```


# Propensity Score

## Logistic Regression 

```{r}
data_model <- data_ %>% 
  .[, .SD, .SDcols = vars_] %>% 
  na.omit 
best_model <- data_model %>% 
  train_model(treatment_name, models='lm')
data_model %<>% cross_fitting(best_model, treatment_name, treatment_vals[1])
```

```{r}
propensities <- data_model %>% 
  .[, .(propensity=propensity, treatment = get(treatment_name))]
auc_result <- auc(roc(propensities$treatment, propensities$propensity))
ggplot(propensities, aes(propensity, fill=treatment, color=treatment)) +
  geom_density(alpha = 0.1) +
  xlim(c(0, 1)) +
  ggtitle('Propensity of being {treatment_vals[1]}\nAUC: {auc_result}' %>% f)
```



## Elastic Net

```{r}
data_model <- data_ %>% 
  .[, .SD, .SDcols = vars_] %>% 
  na.omit
best_model <- data_model %>% 
  as.data.table %>% 
  train_model(treatment_name, models='elastic', tuneLength = tuneLength)
data_model %<>% cross_fitting(best_model, treatment_name, treatment_vals[1])
```

```{r}
propensities <- data_model %>% 
  .[, .(propensity=propensity, treatment = get(treatment_name))]
auc_result <- auc(roc(propensities$treatment, propensities$propensity))
ggplot(propensities, aes(propensity, fill=treatment, color=treatment)) +
  geom_density(alpha = 0.1) +
  xlim(c(0, 1)) +
  ggtitle('Propensity of being {treatment_vals[1]}\nAUC: {auc_result}' %>% f)
```

## Boosting

```{r}
data_model <- data_ %>% 
  .[, .SD, .SDcols = vars_] %>% 
  na.omit
best_model <- data_model %>% 
  as.data.table %>% 
  train_model(treatment_name, models='boosting', tuneLength = tuneLength)
data_model %<>% cross_fitting(best_model, treatment_name, treatment_vals[1])
```

```{r}
propensities <- data_model %>% 
  .[, .(propensity=propensity, treatment = get(treatment_name))]
auc_result <- auc(roc(propensities$treatment, propensities$propensity))
ggplot(propensities, aes(propensity, fill=treatment, color=treatment)) +
  geom_density(alpha = 0.1) +
  xlim(c(0, 1)) +
  ggtitle('Propensity of being {treatment_vals[1]}\nAUC: {auc_result}' %>% f)
```