---
title: "5y complications analysis"
output:
  pdf_document: default
  html_document: default
always_allow_html: yes
---

  
```{r setup, include=FALSE}
knitr::opts_knit$set(
  echo = FALSE, 
  root.dir=normalizePath('../../'),
  warning=FALSE, 
  comment="",
  message=FALSE
)
```

```{r warning=FALSE, echo=FALSE, include=FALSE}
library(stringr)
library(ggplot2)
library(zeallot)
library(gridExtra)
library(DiagrammeR)

source('code/five_years/five_years-utils.R')

ncols_plots <- 2

outcomes <- c(
  '5Y. ODI - Score (%)', '5Y. SRS22 - SRS Subtotal score', '5Y. SF36 - PCS', '5Y. SF36 - MCS'
)

c(data_set_0, predictive_vars, .) %<-% get_data(clean=FALSE)
data_set <- data_set_0 %>% copy

xls_path <- 'data/ESSG extraction December 2020 - DEF.xlsx'

complications <- read_excel(xls_path, sheet='Complications') %>%
  as.data.table %>%
  .[`Complication Impact` == 'Major Complication'] 

reinterventions <- read_excel(XLS_PATH, sheet = "Revision surgeries") %>%
  data.table 

data_set_0 %>% 
  .[, .(
    `Code of the patient`, 
    stage_date=`st1. Date of Stage 1`
  )]  %>% 
  rbind(
    reinterventions %>% 
      .[, .(
        `Code of the patient`, 
        stage_date=`st1. Date of Stage`
      )]    
  ) %>% 
  .[!is.na(stage_date)] %>% 
  .[, diff_years:=difftime(stage_date, min(stage_date), units = "days")/365, 
    `Code of the patient`] %>% 
  .[diff_years > 0] ->
  reinterventions


demographics <- read_yaml('code/five_years/demographic.yml')
demographics_all <- demographics %>% unlist


outcomes %>% 
  lapply(. %>% str_replace_all('5', '2')) ->
  outcomes_2y
names(outcomes_2y) <- outcomes

outcomes %>% 
  lapply(. %>% str_replace_all('5', '3')) ->
  outcomes_3y
names(outcomes_3y) <- outcomes

outcomes %>% 
  lapply(. %>% str_replace_all('5', '6')) ->
  outcomes_6y
names(outcomes_6y) <- outcomes

outcomes %>% 
  sapply(. %>% get_base_outcome(first_visit=TRUE)) ->
  base_outcomes 

for( outcome in names(outcomes_6y)){
  outcome_6y <- outcomes_6y[[outcome]]
  outcome_2y <- outcomes_2y[[outcome]]
  outcome_3y <- outcomes_3y[[outcome]]
  data_set %<>%
    .[is.na(get(outcome)), c(outcome) := get(outcome_6y)] %>% 
    .[is.na(get(outcome_2y)), c(outcome_2y) := get(outcome_3y)]
}

# outcome_2y <- outcomes_2y[[1]]
# outcome <- outcomes[[1]]

study_vars <- c(
  outcomes, outcomes_2y %>% unlist, 
  demographics_all, base_outcomes, 
  'Code of the patient', 
  'Site', 
  'Study', 
  'Vital status', 
  'st1. Date of Stage 1', 
  '2 YEAR VISIT - Date of visit',
  '3 YEAR VISIT - Date of visit',
  '5 YEAR VISIT - Date of visit',
  '6 YEAR VISIT - Date of visit'
) %>% unique
data_set %<>% 
  .[, .SD, .SDcols=study_vars] 
```

### Filters
```{r warning=FALSE }
discarded_patients <- readLines('code/five_years/discarded_patients')

data_set %<>% 
  .[, followup_2y := 
      !is.na(`2 YEAR VISIT - Date of visit`) | 
      !is.na(`3 YEAR VISIT - Date of visit`)] %>% 
  .[, followup_5y := 
      !is.na(`5 YEAR VISIT - Date of visit`) | 
      !is.na(`6 YEAR VISIT - Date of visit`)]

data_set %<>% 
  .[followup_2y==TRUE] %>% 
  .[Site != 'ANK Op'] %>% 
  .[Study=='Op'] %>% 
  .[`Vital status` == 'Alive'] %>% 
  .[!(`Code of the patient` %in% discarded_patients)] %>% 
  .[`st1. Date of Stage 1` %>% as.Date() < as.Date('2015-3-15')]

```

```{r echo=FALSE}
data_set %<>% 
  .[, followup_2y := ifelse(followup_2y == TRUE, 'has_followup', 'no_followup')] %>% 
  .[, followup_5y := ifelse(followup_5y == TRUE, 'has_followup', 'no_followup')] 

patients_all <- data_set[, `Code of the patient` %>% unique]
complications %<>% .[`Code of the patient` %in% patients_all]
reinterventions %<>% .[`Code of the patient` %in% patients_all]
```

#### Only Major Complications


```{r echo=FALSE}
complication_types <- complications[, `Category of the complication` %>% unique]
complication_types <- complication_types %!in% "Central neurologic complications"
```

## All complications
```{r echo=FALSE, comment=""}

patients_complications_5y <- complications %>%
  .[`Days since surgery` >= 365*2 ] %>% 
  .[`Days since surgery` < 365*5 ] %>% 
  .[`Category of the complication` %in% complication_types, `Code of the patient`]
patients_complications_2y <- complications %>%
  .[`Days since surgery` < 365*2 ] %>% 
  .[`Category of the complication` %in% complication_types, `Code of the patient`]

data_ <- data_set %>%
  copy %>%
  .[, complication_before_2y:='No'] %>%
  .[`Code of the patient` %in% patients_complications_2y, complication_before_2y:='Yes'] %>% 
  .[ followup_2y == 'no_followup', complication_before_2y:=NA] %>%
  .[, complication_2y_5y:='No'] %>%
  .[`Code of the patient` %in% patients_complications_5y, complication_2y_5y:='Yes'] %>% 
  .[ followup_5y == 'no_followup', complication_2y_5y:=NA]


htmltools::h3('Major Complications')
models <- variable_effect(data_, 'complication_2y_5y', 'complication_before_2y', demographics)
htmltools::h5('Demographics')
models$demographic %>% print
htmltools::h5('Radiology')
models$radiology %>% print
```



# Impact of complications on followup

Only considering those with 2 FU

```{r echo=FALSE, comment=""}
patients_complications_5y <- complications %>%
  .[`Days since surgery` >= 365*2 ] %>% 
  .[`Days since surgery` < 365*5 ] %>% 
  .[, `Code of the patient`]
patients_complications_2y <- complications %>%
  .[`Days since surgery` < 365*2 ] %>% 
  .[, `Code of the patient`]

data_ <- data_set %>%
  copy %>%
  .[, complication_before_2y:='No'] %>%
  .[`Code of the patient` %in% patients_complications_2y, complication_before_2y:='Yes'] %>% 
  .[ followup_2y == FALSE, complication_before_2y:=NA] %>%
  .[, complication_2y_5y:='No'] %>%
  .[`Code of the patient` %in% patients_complications_5y, complication_2y_5y:='Yes'] %>% 
  .[ followup_5y == FALSE, complication_2y_5y:=NA]


data_[
  followup_2y=='has_followup'
][,
  .SD, .SDcols=c(demographics_all, 'complication_before_2y', 'followup_5y')
][,
  followup_5y := ifelse(followup_5y=='has_followup', 1, 0)
]  %>% 
glm(followup_5y~., data=.) %>% summary
```


## Complication Types

```{r echo=FALSE}
complication_type <- complication_types[1]

# demo_plots <- plot_complications(complication_type, complications, data_set, demographics_all)
```

```{r echo=FALSE, message=FALSE, fig.height=30, fig.width=10, warning=FALSE}
# htmltools::h1(complication_type)
# do.call("grid.arrange", c(demo_plots, ncol=ncols_plots))
```

```{r echo=FALSE, comment=""}
patients_complications_5y <- complications %>%
  .[`Days since surgery` >= 365*2 ] %>% 
  .[`Days since surgery` < 365*5 ] %>% 
  .[`Category of the complication` == complication_type, `Code of the patient`]
patients_complications_2y <- complications %>%
  .[`Days since surgery` < 365*2 ] %>% 
  .[`Category of the complication` == complication_type, `Code of the patient`]

data_ <- data_set %>%
  copy %>%
  .[, complication_before_2y:='No'] %>%
  .[`Code of the patient` %in% patients_complications_2y, complication_before_2y:='Yes'] %>% 
  .[ followup_2y == 'no_followup', complication_before_2y:=NA] %>%
  .[, complication_2y_5y:='No'] %>%
  .[`Code of the patient` %in% patients_complications_5y, complication_2y_5y:='Yes'] %>% 
  .[ followup_5y == 'no_followup', complication_2y_5y:=NA]


htmltools::h3(complication_type)
models <- variable_effect(data_, 'complication_2y_5y', 'complication_before_2y', demographics)
htmltools::h5('Demographics')
models$demographic %>% print
htmltools::h5('Radiology')
models$radiology %>% print
```

```{r echo=FALSE}
complication_type <- complication_types[2]

# demo_plots <- plot_complications(complication_type, complications, data_set, demographics_all)
```

```{r echo=FALSE, message=FALSE, fig.height=30, fig.width=10, warning=FALSE}
# htmltools::h1(complication_type)
# do.call("grid.arrange", c(demo_plots, ncol=ncols_plots))
```

```{r echo=FALSE, comment=""}
patients_complications_5y <- complications %>%
  .[`Days since surgery` >= 365*2 ] %>% 
  .[`Days since surgery` < 365*5 ] %>% 
  .[`Category of the complication` == complication_type, `Code of the patient`]
patients_complications_2y <- complications %>%
  .[`Days since surgery` < 365*2 ] %>% 
  .[`Category of the complication` == complication_type, `Code of the patient`]

data_ <- data_set %>%
  copy %>%
  .[, complication_before_2y:='No'] %>%
  .[`Code of the patient` %in% patients_complications_2y, complication_before_2y:='Yes'] %>% 
  .[ followup_2y == 'no_followup', complication_before_2y:=NA] %>%
  .[, complication_2y_5y:='No'] %>%
  .[`Code of the patient` %in% patients_complications_5y, complication_2y_5y:='Yes'] %>% 
  .[ followup_5y == 'no_followup', complication_2y_5y:=NA]


htmltools::h3(complication_type)
models <- variable_effect(data_, 'complication_2y_5y', 'complication_before_2y', demographics)
htmltools::h5('Demographics')
models$demographic %>% print
htmltools::h5('Radiology')
models$radiology %>% print
```


```{r echo=FALSE}
complication_type <- complication_types[3]

# demo_plots <- plot_complications(complication_type, complications, data_set, demographics_all)
```

```{r echo=FALSE, message=FALSE, fig.height=30, fig.width=10, warning=FALSE}
# htmltools::h1(complication_type)
# do.call("grid.arrange", c(demo_plots, ncol=ncols_plots))
```

```{r echo=FALSE, comment=""}
patients_complications_5y <- complications %>%
  .[`Days since surgery` >= 365*2 ] %>% 
  .[`Days since surgery` < 365*5 ] %>% 
  .[`Category of the complication` == complication_type, `Code of the patient`]
patients_complications_2y <- complications %>%
  .[`Days since surgery` < 365*2 ] %>% 
  .[`Category of the complication` == complication_type, `Code of the patient`]

data_ <- data_set %>%
  copy %>%
  .[, complication_before_2y:='No'] %>%
  .[`Code of the patient` %in% patients_complications_2y, complication_before_2y:='Yes'] %>% 
  .[ followup_2y == 'no_followup', complication_before_2y:=NA] %>%
  .[, complication_2y_5y:='No'] %>%
  .[`Code of the patient` %in% patients_complications_5y, complication_2y_5y:='Yes'] %>% 
  .[ followup_5y == 'no_followup', complication_2y_5y:=NA]


htmltools::h3(complication_type)
models <- variable_effect(data_, 'complication_2y_5y', 'complication_before_2y', demographics)
htmltools::h5('Demographics')
models$demographic %>% print
htmltools::h5('Radiology')
models$radiology %>% print
```

```{r echo=FALSE}
complication_type <- complication_types[4]

# demo_plots <- plot_complications(complication_type, complications, data_set, demographics_all)
```

```{r echo=FALSE, message=FALSE, fig.height=30, fig.width=10, warning=FALSE}
# htmltools::h1(complication_type)
# do.call("grid.arrange", c(demo_plots, ncol=ncols_plots))
```

```{r echo=FALSE, comment=""}
patients_complications_5y <- complications %>%
  .[`Days since surgery` >= 365*2 ] %>% 
  .[`Days since surgery` < 365*5 ] %>% 
  .[`Category of the complication` == complication_type, `Code of the patient`]
patients_complications_2y <- complications %>%
  .[`Days since surgery` < 365*2 ] %>% 
  .[`Category of the complication` == complication_type, `Code of the patient`]

data_ <- data_set %>%
  copy %>%
  .[, complication_before_2y:='No'] %>%
  .[`Code of the patient` %in% patients_complications_2y, complication_before_2y:='Yes'] %>% 
  .[ followup_2y == 'no_followup', complication_before_2y:=NA] %>%
  .[, complication_2y_5y:='No'] %>%
  .[`Code of the patient` %in% patients_complications_5y, complication_2y_5y:='Yes'] %>% 
  .[ followup_5y == 'no_followup', complication_2y_5y:=NA]


htmltools::h3(complication_type)
models <- variable_effect(data_, 'complication_2y_5y', 'complication_before_2y', demographics)
htmltools::h5('Demographics')
models$demographic %>% print
htmltools::h5('Radiology')
models$radiology %>% print
```



# Reinterventions

```{r echo=FALSE, comment=""}

reinterventions_2y <- reinterventions %>%
  .[diff_years < 2, .(reinterventions_before_2y=.N*1.0), `Code of the patient`]
reinterventions_5y <- reinterventions %>%
  .[2 <= diff_years & diff_years <= 5, .(reinterventions_2y_5y=.N*1.0), `Code of the patient`]


data_ <- data_set %>%
  copy %>%
  merge(reinterventions_2y, all.x=TRUE, all.y=FALSE, by="Code of the patient") %>% 
  .[is.na(reinterventions_before_2y), reinterventions_2y:= 0] %>% 
  merge(reinterventions_5y, all.x=TRUE, all.y=FALSE, by="Code of the patient") %>% 
  .[is.na(reinterventions_2y_5y), reinterventions_2y_5y:= 0]
  
htmltools::h3('Number of reinterventions')
models <- variable_effect(data_, 'reinterventions_2y_5y', 'reinterventions_before_2y', demographics)
htmltools::h5('Demographics')
models$demographic %>% print
htmltools::h5('Radiology')
models$radiology %>% print
```


