---
title: "Clusters Descriptives"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include=FALSE, message=FALSE, warning=FALSE, comment="")
```

```{r}
library(data.table)
library(magrittr)
library(yaml)
library(stats)

source('patient_selection.R')
source('clusters_aux.R')
```

```{r, message=FALSE}
data_ <- get_data_base()
cluster_vars <- read_yaml('cluster_vars.yml')
analysis_vars <- read_yaml('descriptive.yml')
cluster_num <- 3
```


```{r echo=TRUE}
data_ %>% 
  # .[followup_2y==TRUE] %>% 
  # .[`st1. Date of Stage` %>% as.Date() < as.Date('2015-09-01')] %>% 
  .[Study=='Op'] %>% 
  .[Site != 'ANK Op'] %>% 
  .[`Vital status` == 'Alive'] -> 
  data_
```
Initial Patients: `r data_[, .N]`

```{r, message=FALSE}
data_ %>% 
  .[, .SD, .SDcols = cluster_vars$vars] %>% 
  scale %>% 
  dist %>% 
  hclust(method="ward.D2") ->
  clusters

data_[, cluster := as.factor(cutree(clusters,k=cluster_num))]
```

Number of patients
```{r include=TRUE}
data_[, .N, cluster]
```


```{r}
treatment_ <- 'cluster'
treatment_vals <- data_[, levels(cluster)]
treatments_n <- len(treatment_vals)
```

```{r}
data_treats <- list()
for(val_ in treatment_vals){
  data_treats[[val_]] <- data_[get(treatment_) == val_]
}
```


### Demographics
```{r echo=FALSE, comment="", include=TRUE}
res_vars_cats <- list()
res_vars_num <- list()
for(var_ in analysis_vars$demographics ){
  
  res_treats <- list()
  res_treats[['All']] <- stats_fun(data_[[var_]])
  for(val_ in treatment_vals){
    res_treats[[val_]] <- stats_fun(data_treats[[val_]][[var_]])
  }
  
  if( is.numeric(data_[[var_]]) ){
    p_vals_list <- list()
    for(val_1_pos in 1:(treatments_n - 1)){
      val_1 <- treatment_vals[val_1_pos]
      p_vals_list[[val_1]] <- list()
      for(val_2_pos in (val_1_pos+1):treatments_n){
        val_2 <- treatment_vals[val_2_pos]
        p.val <- calc_p_vals(
          data_, var_, treatment_, c(val_1, val_2)
        ) %>% round(4)
        if( is.null(p.val) ) p.val <- NA
        p_vals_list[["p.val_{val_1}" %>% f]][[val_2]] <- p.val
      }
    }
    
    res_vars_num[[var_]] <- cbind(
      variable = var_,
      res_treats %>% unlist %>% t %>% as.data.frame(),
      p_vals_list %>% unlist %>% t %>% as.data.frame()
    )
    
    formula_ <- "`{var_}`~cluster" %>% f %>% as.formula
    aov_res <- aov(formula_, data_)
    res_vars_num[[var_]]$p.val_all <- summary(aov_res)[[1]][["Pr(>F)"]][1] %>% 
      round(4)
  }else{
    res_vars_cats[[var_]] <- res_treats
  }
}
```

```{r include=TRUE}
do.call(rbind, res_vars_num)
```

```{r include=TRUE}
print(res_vars_cats)
```


### Radiology
```{r echo=FALSE, comment="", include=TRUE}
for(var_ in analysis_vars$radiology ){
  var_6w <- "6W. {var_}" %>% f
  var_6m <- "6M. {var_}" %>% f
  var_1y <- "1Y. {var_}" %>% f
  var_2y <- "2Y. {var_}" %>% f
  var_5y <- "5Y. {var_}" %>% f
  vars_years <- c(var_, var_6w, var_6m, var_1y, var_2y, var_5y)
  res_vars_num <- list()
  res_treats <- list()
  for(var_y in vars_years){
    res_treats[['All']] <- stats_fun(data_[[var_y]])
    for(val_ in treatment_vals){
      res_treats[[val_]] <- stats_fun(data_treats[[val_]][[var_y]])
    }
    
    p_vals_list <- list()
    for(val_1_pos in 1:(treatments_n - 1)){
      val_1 <- treatment_vals[val_1_pos]
      p_vals_list[[val_1]] <- list()
      for(val_2_pos in (val_1_pos+1):treatments_n){
        val_2 <- treatment_vals[val_2_pos]
        p.val <- calc_p_vals(data_, var_y, treatment_, c(val_1, val_2)) %>% 
          round(4)
        if( is.null(p.val) ) p.val <- NA
        p_vals_list[["p.val_{val_1}" %>% f]][[val_2]] <- p.val
      }
    }
    
    res_vars_num[[var_y]] <- cbind(
      res_treats %>% unlist %>% t %>% as.data.frame(),
      p_vals_list %>% unlist %>% t %>% as.data.frame()
    )
    
    formula_ <- "`{var_y}`~cluster" %>% f %>% as.formula
    aov_res <- aov(formula_, data_)
    res_vars_num[[var_y]]$p.val_all <- summary(aov_res)[[1]][["Pr(>F)"]][1] %>% 
      round(4)
  }
  
  cat('\n\n\n')
  print(var_)
   cat('\n')
  print(do.call(rbind, res_vars_num))
  
  res_time_p <- list()
  res_time_p[['All']] <- calc_time_p_values(
    data_, var_, var_6w, var_2y, var_5y, cluster_name='All'
  )
  for(val_ in treatment_vals){
    res_time_p[[val_]] <- calc_time_p_values(
      data_treats[[val_]], var_, var_6w, var_2y, var_5y, cluster_name=val_
    )
  }
  
  do.call(rbind, res_time_p) %>% 
    as.data.table() %>% 
    dcast(t0 + t1 ~ group, value.var='p.val') %>% 
    setorder(-"t0") ->
    res_time_p
  
  cat('\n')
  print(res_time_p)
}
```


### Quality of Life
```{r echo=FALSE, comment="", include=TRUE}
for(var_ in analysis_vars$quality ){
  var_6m <- "6M. {var_}" %>% f
  var_1y <- "1Y. {var_}" %>% f
  var_2y <- "2Y. {var_}" %>% f
  var_5y <- "5Y. {var_}" %>% f
  vars_years <- c(var_, var_6m, var_1y, var_2y, var_5y)
  res_vars_num <- list()
  res_treats <- list()
  for(var_y in vars_years){
    res_treats[['All']] <- stats_fun(data_[[var_y]])
    for(val_ in treatment_vals){
      res_treats[[val_]] <- stats_fun(data_treats[[val_]][[var_y]])
    }
    
    p_vals_list <- list()
    for(val_1_pos in 1:(treatments_n - 1)){
      val_1 <- treatment_vals[val_1_pos]
      p_vals_list[[val_1]] <- list()
      for(val_2_pos in (val_1_pos+1):treatments_n){
        val_2 <- treatment_vals[val_2_pos]
        p.val <- calc_p_vals(data_, var_y, treatment_, c(val_1, val_2)) %>% 
          round(4)
        if( is.null(p.val) ) p.val <- NA
        p_vals_list[["p.val_{val_1}" %>% f]][[val_2]] <- p.val
      }
    }
    
    res_vars_num[[var_y]] <- cbind(
      res_treats %>% unlist %>% t %>% as.data.frame(),
      p_vals_list %>% unlist %>% t %>% as.data.frame()
    )
    
    formula_ <- "`{var_y}`~cluster" %>% f %>% as.formula
    aov_res <- aov(formula_, data_)
    res_vars_num[[var_y]]$p.val_all <- summary(aov_res)[[1]][["Pr(>F)"]][1] %>% 
      round(4)
  }
  
  cat('\n\n\n')
  print(var_)
  cat('\n')
  print(do.call(rbind, res_vars_num))
  
  res_time_p <- list()
  res_time_p[['All']] <- calc_time_p_values(
    data_, var_, var_6m, var_2y, var_5y, cluster_name='All'
  )
  for(val_ in treatment_vals){
    res_time_p[[val_]] <- calc_time_p_values(
      data_treats[[val_]], var_, var_6m, var_2y, var_5y, cluster_name=val_
    )
  }
  
  do.call(rbind, res_time_p) %>% 
    as.data.table() %>% 
    dcast(t0 + t1 ~ group, value.var='p.val') %>% 
    setorder(-"t0") ->
    res_time_p
  
  cat('\n')
  print(res_time_p)
}
```


### Surgery

```{r echo=FALSE, comment="", include=TRUE}
res_vars_cats <- list()
res_vars_num <- list()
for(var_ in analysis_vars$surgery  ){
  
  res_treats <- list()
  res_treats[['All']] <- stats_fun(data_[[var_]])
  for(val_ in treatment_vals){
    res_treats[[val_]] <- stats_fun(data_treats[[val_]][[var_]])
  }
  
  if( is.numeric(data_[[var_]]) ){
    p_vals_list <- list()
    for(val_1_pos in 1:(treatments_n - 1)){
      val_1 <- treatment_vals[val_1_pos]
      p_vals_list[[val_1]] <- list()
      for(val_2_pos in (val_1_pos+1):treatments_n){
        val_2 <- treatment_vals[val_2_pos]
        p.val <- calc_p_vals(data_, var_, treatment_, c(val_1, val_2)) %>% 
          round(4)
        if( is.null(p.val) ) p.val <- NA
        p_vals_list[["p.val_{val_1}" %>% f]][[val_2]] <- p.val
      }
    }
    
    res_vars_num[[var_]] <- cbind(
      res_treats %>% unlist %>% t %>% as.data.frame(),
      p_vals_list %>% unlist %>% t %>% as.data.frame()
    )
    
    formula_ <- "`{var_}`~cluster" %>% f %>% as.formula
    aov_res <- aov(formula_, data_)
    res_vars_num[[var_]]$p.val_all <- summary(aov_res)[[1]][["Pr(>F)"]][1] %>% 
      round(4)
  }else{
    res_vars_cats[[var_]] <- res_treats
  }
}
```

```{r}
do.call(rbind, res_vars_num)
```

```{r}
print(res_vars_cats)
```

<!-- # Reinterventions -->

<!-- ```{r} -->
<!-- res <- calc_complications(data_, treatment_vals) -->
<!-- ``` -->

<!-- ```{r include=TRUE} -->
<!-- res$number_reiqs -->
<!-- ``` -->

<!-- ```{r include=TRUE} -->
<!-- res$p_vals_reiqs -->
<!-- ``` -->

<!-- # Impacts -->

<!-- ```{r include=TRUE} -->
<!-- res$impacts -->
<!-- ``` -->

<!-- # Categories -->

<!-- ```{r include=TRUE} -->
<!-- res$categories -->
<!-- ``` -->


