---
title: "ALIF EXPLORATION"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(
  echo = TRUE, 
  root.dir=normalizePath('../../')
)
```

```{r warning=FALSE, include=FALSE}
library(data.table)
library(magrittr)
library(kableExtra)
library(zeallot)
library(yaml)


source('code/alif/alif-utils.R')
source('code/propensity-utils.R')

tuneLenghtPropensity <- 40
modelsPropensity <- c('elastic')
tuneLenghtATE <- 5
modelsATE <- c('boosting')
replicas_boot <- 200L
propensity_trim <- 0.5
repetitions <- 200

c(sel_data, matching_vars) %<-% get_data(evaluation=TRUE)
covariates_data <- sel_data[, .SD, .SDcols=matching_vars$covariates]
treatment_name <- 'Alif'
```

### Selected Variables

```{r echo=FALSE, comment=""}
cat(matching_vars %>% as.yaml)
```

```{r echo=FALSE, warning=FALSE, results="asis"}
# explore_vars(covariates_data, treatment_name=treatment_name)
```


## Propensity Scores Common Support
```{r echo=FALSE, warning=FALSE}
prop_data <- copy(covariates_data)
prop_data[['patient_id']] <- sel_data[, `Code of the patient`]
run_propensity(
  prop_data,
  treatment_name=treatment_name,
  tuneLength = tuneLenghtPropensity,
  models = modelsPropensity
) -> best_model

```

#### Model Stats

- Treatment proportion: `r mean(covariates_data[[treatment_name]] == 'Yes') %>% round(3)`
- Model Type: `r best_model$sel_model`
- Accuracy: `r best_model$accuracy`
- Params: `r as.yaml(best_model$params)`


<!-- ```{r echo=FALSE} -->
<!-- print(best_model$plot) -->
<!-- ``` -->

<!-- ## Model Coefficients -->

<!-- Bootstraping replicas: `r replicas_boot`, confidence intervals at 95% level -->

<!-- ```{r echo=FALSE, fig.height=9, fig.width=10, comment=""} -->
<!-- c(data_plot, table_ci) %<-% plot_coefs(treatment_name, covariates_data, best_model, replicas_boot) -->

<!-- print(data_plot) -->
<!-- ``` -->


<!-- ```{r echo=FALSE, fig.height=9, fig.width=10, comment=""} -->
<!-- table_ci %>%  -->
<!--   as.data.frame %>%  -->
<!--   DT::datatable() -->
<!-- ``` -->



```{r echo=FALSE}
propensities <- best_model$clean_data %>%
  .[, .(patient_id, Propensity)] %>%
  setnames("patient_id", "Code of the patient")

sel_data %>%
  merge(propensities, by='Code of the patient', all.x=TRUE) %>%
  setorder(-Propensity) ->
  ate_data
```

```{r warning=FALSE, echo=FALSE, comment="", include=FALSE}
demographics <- matching_vars$demographic
predictive_variates <- c(treatment_name, 'Propensity', demographics) %>% unique
```


# Average Treatment Effects - Reintervention Number

```{r ate_reintervention, warning=FALSE, echo=FALSE, comment="", include=FALSE}
xls_path <- 'data/ESSG extraction July 2020_3.xlsx'
# excel_sheets(xls_path)

rev_patient_data <- read_excel(xls_path, sheet = "Rev surgeries") %>%
  data.table %>%
  .[, .(reinterventions=.N), `Code of the patient`]

data_ <- ate_data %>%
  copy %>%
  merge(rev_patient_data, by="Code of the patient", all.x=TRUE, all.y=FALSE) %>%
  .[is.na(reinterventions), reinterventions:=0] %>% 
  .[, reinterventions := reinterventions * 1.0]
  # .[reinterventions > 0] %>%
  # .[, `Code of the patient`:=NULL]

outcome <- 'reinterventions'
is_classification <- FALSE
# predictive_variates <- c(treatment_name, 'Propensity')
# predictive_variates <- c(
#   matching_vars$covariates, matching_vars$predictive, 'Propensity'
# ) %>% unique
results <- calc_ate(
  data_, outcome, treatment_name=treatment_name,
  predictive_variates, first_visit=FALSE,
  tuneLenghtATE, modelsATE, incremental=FALSE, is_classification, repetitions
)
```

```{r echo=FALSE, warning=FALSE, comment=""}
print_ates(treatment_name, outcome, results, is_classification, propensity_trim, demographics)
```

# Average Treatment Effects - Had Reintervention

```{r ate_reintervention_bool, warning=FALSE, echo=FALSE, comment="", include=FALSE}
xls_path <- 'data/ESSG extraction July 2020_3.xlsx'
# excel_sheets(xls_path)

rev_patients <- read_excel(xls_path, sheet = "Rev surgeries") %>%
  data.table %>%
  .[, unique(`Code of the patient`)]

data_ <- ate_data %>%
  copy %>%
  .[, had_reintervention := 'No'] %>%
  .[`Code of the patient` %in% rev_patients, had_reintervention := 'Yes']

outcome <- 'had_reintervention'
is_classification <- TRUE
# predictive_variates <- c(treatment_name, 'Propensity')
results <- calc_ate(
  data_, outcome, treatment_name=treatment_name,
  predictive_variates, first_visit=FALSE,
  tuneLenghtATE, modelsATE, incremental=FALSE, is_classification, repetitions
)
```

```{r echo=FALSE, warning=FALSE, comment=""}
print_ates(treatment_name, outcome, results, is_classification, propensity_trim, demographics)
```