---
title: "ALIF EXPLORATION"
output:
  pdf_document: default
  html_document: default
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_knit$set(
  echo = TRUE, 
  root.dir=normalizePath('../../')
)
```

```{r warning=FALSE, include=FALSE}
library(data.table)
library(magrittr)
library(kableExtra)
library(zeallot)
library(yaml)


source('code/alif/alif-utils.R')
source('code/propensity-utils.R')

tuneLenghtPropensity <- 40
modelsPropensity <- c('elastic')
tuneLenghtATE <- 8
modelsATE <- c('boosting')
replicas_boot <- 200L
propensity_trim <- 0.5
repetitions <- 100

c(sel_data, matching_vars) %<-% get_data(evaluation=TRUE)
covariates_data <- sel_data[, .SD, .SDcols=matching_vars$covariates]
treatment_name <- 'Alif'
```

### Selected Variables

```{r echo=FALSE, comment=""}
cat(matching_vars %>% as.yaml)
```

```{r echo=FALSE, warning=FALSE, results="asis"}
# explore_vars(covariates_data, treatment_name=treatment_name)
```


## Propensity Scores Common Support
```{r echo=FALSE, warning=FALSE}
prop_data <- copy(covariates_data)
prop_data[['patient_id']] <- sel_data[, `Code of the patient`]
run_propensity(
  prop_data,
  treatment_name=treatment_name,
  tuneLength = tuneLenghtPropensity,
  models = modelsPropensity
) -> best_model

```

#### Model Stats

- Treatment proportion: `r mean(covariates_data[[treatment_name]] == 'Yes') %>% round(3)`
- Model Type: `r best_model$sel_model`
- Accuracy: `r best_model$accuracy`
- Params: `r as.yaml(best_model$params)`


<!-- ```{r echo=FALSE} -->
<!-- print(best_model$plot) -->
<!-- ``` -->

<!-- ## Model Coefficients -->

<!-- Bootstraping replicas: `r replicas_boot`, confidence intervals at 95% level -->

<!-- ```{r echo=FALSE, fig.height=9, fig.width=10, comment=""} -->
<!-- c(data_plot, table_ci) %<-% plot_coefs(treatment_name, covariates_data, best_model, replicas_boot) -->

<!-- print(data_plot) -->
<!-- ``` -->


<!-- ```{r echo=FALSE, fig.height=9, fig.width=10, comment=""} -->
<!-- table_ci %>%  -->
<!--   as.data.frame %>%  -->
<!--   DT::datatable() -->
<!-- ``` -->



```{r echo=FALSE}
propensities <- best_model$clean_data %>%
  .[, .(patient_id, Propensity)] %>%
  setnames("patient_id", "Code of the patient")

sel_data %>%
  merge(propensities, by='Code of the patient', all.x=TRUE) %>%
  setorder(-Propensity) ->
  ate_data
```


# Average Treatment Effects - Quality Life

```{r warning=FALSE, echo=FALSE, comment="", include=FALSE}
demographics <- matching_vars$demographic
predictive_variates <- c(treatment_name, 'Propensity', demographics) %>% unique
```


```{r ate_ql, warning=FALSE, echo=FALSE, comment="", include=FALSE}
outcomes <- matching_vars$outcomes_ql

# predictive_variates <- c(matching_vars$covariates, matching_vars$predictive) %>% unique
results_outcomes <- list()
for(outcome in outcomes){
  is_classification <- class(ate_data[[outcome]]) %in% c('character', 'factor')
  results_outcomes[[outcome]] <- calc_ate(
    ate_data, outcome, treatment_name=treatment_name,
    predictive_variates, first_visit=TRUE,
    tuneLenghtATE, modelsATE, incremental=TRUE, is_classification, repetitions
  )
}
```

```{r echo=FALSE, warning=FALSE, comment=""}
for(outcome in outcomes){
  is_classification <- class(sel_data[[outcome]]) %in% c('character', 'factor')
  print_ates(treatment_name, outcome, results_outcomes[[outcome]], is_classification,
    propensity_trim, demographics)
}
```
